### ISSUE TITLE
Group::load() and save() should return a success value

### ISSUE THREAD

**Issue by agcapps** [LLNL/axom#101]
The lack of a success return value was a mistake in our design.

**Comment by agcapps** [comment]
OK, that opening comment was off-target.  `Group::load()` and `save()` wrap Conduit's `relay::io::load()` and `save()`.  Those functions use exceptions to report problems.  If it didn't throw an exception, it went OK.  In Sidre, we re-wire "throw exception" to "call a function that calls a `slic` logging function."

Maybe what we need to do is discuss this design choice in the documentation and example codes.  Possibly we could have the handler functions store an error state and message, sort of "my very own sidre errno", with getters to make this state accessible to C and Fortran.  As @cyrush pointed out, this does tend to get messy.

**Comment by rhornung67** [comment]
Try to find time to discuss options as a group.
