### ISSUE TITLE
Document meaning of Sidre I/O protocols

### ISSUE THREAD

**Issue by nselliott** [LLNL/axom#1019]
https://github.com/LLNL/axom/issues/97 points out that not all of the protocols used for `sidre::Group`'s save/load methods (which in turn are used by spio `IOManager`) are tested for round-trip equivalence. We do test the `sidre_hdf5` protocol and have some less extensive testing for other protocols.

The fact is that some of the protocols cannot be guaranteed to preserve round-trip equivalence, because they don't preserve enough information in the save to provide the load with enough information to reconstruct identical objects.  The most clear example is the `json` protocol which writes scalar values in plain text without any detailed type information such as bit-width.  However, some of the protocols are capable of round-trip equivalence but aren't tested for this as fully as `sidre_hdf5`.

Another thing that we lack is any documentation of what all of the protocols mean and what users should expect when they choose one or another.

Action items for this issue:

- [x] Write documentation of the protocols to explain the meaning and expectations for each.
- [x] Extend the save/load round-trip testing to test all protocols that can do round-trip equivalence.
- [x] Review the save/load testing for the other protocols to make sure their capabilities are sufficiently covered.

This issue supersedes #97 which will now be closed.

**Comment by nselliott** [comment]
My conclusions from reviewing the save/load round-trip testing:

- Of the supported protocols, only `sidre_hdf5` preserves full accuracy in a round-trip operation.  This means it restores the datatype schema for all Views, it maintains the state of all Buffers and the relationships between Buffers and Views, and it preserves binary accuracy of floating point values.

- The three ways certain protocols fall short of round-trip equivalence are: Some don't write out datatype schemas for Views, so on loading the code must use defaults for constructing datatypes; some don't output Buffers separate from the Views, so if there was a shared Buffer in the original DataStore, its data is duplicated in the loaded version; and the plain-text floating-point values stored in JSON protocols will produce round-off differences.  These are all inherent in how the protocols are defined, and I have attempted to document them in the documentation that has already been merged.

- All protocols preserve the core Group/View hierarchy in round-trip operations.

- We have round-trip testing for all protocols, but the tests are set up in a way to avoid the parts of round-trip equivalence that certain protocols can't guarantee.  Datatypes are chosen in the original DataStore to be the default types that will be used by the protocols that don't preserve datatype schemas, and floating-point values are tested using EXPECT_NEAR.

I think this is sufficient testing coverage and documentation for round-trip operations in all of the protocols, but I am open to suggestions.

**Comment by rhornung67** [comment]
@nselliott thanks for the detailed summary. I think what we have now is fine unless there is a good reason to enhance the bookkeeping to ensure protocols other than sidre_hdf5 preserve state for save/load round-trip. Do we know if any users have asked for such a capability?

**Comment by nselliott** [comment]
@rhornung67 I'm not aware of any user requests. `sidre_conduit_json` is the next closest to preserving everything--it only falls short with the plain-text floating point round-off.
