### ISSUE TITLE
Enhance Axom so the shaping driver can write data that includes matsets for visualization.

### ISSUE THREAD

**Issue by BradWhitlock** [LLNL/axom#1050]
The shaping driver writes out materials as a set of scalar volume fraction arrays. Make it also write out the matset information needed so VisIt can interpret the material data as real materials so plots like FilledBoundary work.

**Comment by BradWhitlock** [comment]
I have some minor changes on a branch that make some progress here. It came down to telling the shaping driver that it needs to associate field names with certain prefixes (vol_frac_) with a material. Then MFEMSidreDataCollection needed some new code to write some matset metadata into the index file.
![axom_save_blueprint_matset](https://user-images.githubusercontent.com/2072964/225492425-b1e21225-867c-46e4-b0fa-5611fa5784a1.png)

**Comment by BradWhitlock** [comment]
Here's a better picture of case5 from the test suite.
![axom_shaping_case5](https://user-images.githubusercontent.com/2072964/225696638-093a5ff8-7045-4cef-95c2-6cae2e976b25.png)

**Comment by BradWhitlock** [comment]
I made sure it works for the sampling shaper too. No changes needed.
![axom_save_blueprint_matset_2d](https://user-images.githubusercontent.com/2072964/225782463-5b31b152-7034-418d-919e-b28cd9bfd0f2.png)

**Comment by kennyweiss** [comment]
Regarding the sampling shaper, presumably that only works for linear meshes, right?
As far as I know, VisIt's MIR capabilities do not work with high order meshes.

Should we add an option to the shaping example to convert the results to a low-order refined (LOR) version to unlock MIR in VisIt? 

A potentially more useful idea might be to add a separate tool to axom that reads in an HO blueprint mesh and outputs an LOR version.

(We can also do both).

**Comment by BradWhitlock** [comment]
Hi Kenny, I don't know what VisIt would do if given HO volume fraction fields - probably something bad. I had been running the shaping driver with "-o 0" for these tests and overlooked higher values. Forcing the volume fraction fields to linear (or making a linear set of fields strictly for materials) when VisIt will be used makes sense to me. That, or making VisIt support HO fields for materials.
