### ISSUE TITLE
Hanging shaping unit tests

### ISSUE THREAD

**Issue by bmhan12** [LLNL/axom#1089]
The `quest_intersection_shaper_tests` are hanging on rzvernal.

They successfully complete if I [undo the unused warning changes to SLIC macros with HIP](https://github.com/LLNL/axom/blame/b3378f48cd18dcf285049a11486b640914bb2fc6/src/axom/slic/interface/slic_macros.hpp#L495-L526), but that brings back the hundreds of unused variable warnings messages.

Currently exploring alternative fixes.

P.S. / PSA:

Our Gitlab CI `tioga` job is allowed to fail due to its fluctuating stability. Rzvernal is relatively more stable, and should be used to test PR's when the `tioga` job is not working properly.

**Comment by kennyweiss** [comment]
Thanks for finding and reporting this @bmhan12 

In the immediate term, I'd think that compiler warnings are better than hanging tests/examples, so I'd suggest reverting if a solution doesn't immediately present itself.

Tag: @BradWhitlock
