### ISSUE TITLE
Libunwind version on toss4 (ruby, corona)

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/axom#1097]
It looks like there were failures with libunwind as an external at some points.
But I also note that the commented external was specifying version 1.3.1, while the system one is 8.0.1 like on other machines.
I’ll be trying to use libunwind 8.0.1 on my side (caliper) and report here.

https://github.com/LLNL/axom/blob/a5b9b2239020df6283adb804532c691a5924904d/scripts/spack/configs/toss_4_x86_64_ib/spack.yaml#L191

**Comment by adrienbernede** [comment]
... It looks like there is no such thing as libunwind@8.0.1

And indeed:
```
> pkg-config --modversion libunwind
1.3.1
`

**Comment by adrienbernede** [comment]
Related to clang, I found another libunwind here:

`/usr/tce/packages/clang/clang-14.0.6/lib/libunwind.so -> /usr/tce/backend/installations/linux-rhel8-x86_64/gcc-10.3.1/llvm-14.0.6-fl3d6cggvip6aja2ttejp2emq6b3mxy3/lib/libunwind.so`

But I don’t know how this could help.

**Comment by white238** [comment]
Serac ran into the following build error with caliper on clang@14.0.6:

```
     589    spack/lib/spack/env/clang/clang++ -O3 -DNDEBUG CMakeFiles/cali-stat.dir/cali-stat.cpp.o -o cali-stat  ../util/libcaliper-tools-util.a ../../libcaliper-serial.a /usr/lib64/libdw.so /usr/tce/packages/clang/clang-14.0.6/lib/libunwind.so lib/libadiak.a /usr/tce/packages/mvapich2/mvapich2-2.3.6-clang-14.0.6/lib/libmpi.so /usr/tce/packages/mvapich2/mvapich2-2.3.6-clang-14.0.6/lib/libmpicxx.so -ldl /usr/lib64/librt.so -pthread
     590    /opt/rh/gcc-toolset-10/root/usr/lib/gcc/x86_64-redhat-linux/10/../../../../bin/ld: ../../libcaliper-serial.a(Callpath.cpp.o): in function `(anonymous namespace)::Callpath::callpath_service_register(cali::Caliper*, cali::Channel*)':
  >> 591    Callpath.cpp:(.text+0x491): undefined reference to `_Ux86_64_getcontext'
```

I honestly have no idea why only clang but not gcc ran into this but turning off the external solved this issue.
