### ISSUE TITLE
Deprecate GPUCC

### ISSUE THREAD

**Issue by agcapps** [LLNL/axom#1101]
`AXOM_GPUCC` is defined in core/Macros.hpp if either `__CUDACC__` or `__HIPCC__` is defined.  That is, if we are compiling under either nvcc or hip.  This macro is probably not needed: we should remove it when we're sure we don't need it.

**Comment by kennyweiss** [comment]
@agcapps -- Can you please clarify why `AXOM_GPUCC` might be unnecessary? 

1. Is it b/c we can just check using the longer `#if defined(__CUDACC__) || defined(__HIPCC)` rather than `#if defined(AXOM_GPUCC)`?
2. Or, is it because we rarely need to guard both at the same time (using `#if defined(__CUDACC__) || defined(__HIPCC)`)? I.e. `cuda` parts are typically guarded by `#if defined(__CUDACC__)`, while `hip` parts are typically guarded by `#if defined(__HIPCC)`  ?
3. Or is it something else?

**Comment by bmhan12** [comment]
>  Can you please clarify why AXOM_GPUCC might be unnecessary?

@kennyweiss  Here's the [discussion point I brought up](https://github.com/LLNL/axom/pull/1100#discussion_r1204404635) that will provide more context.

Essentially, with the way Axom now builds with HIP/CUDA using CMake, `AXOM_GPUCC` is redundant to `AXOM_USE_GPU`.

**Comment by agcapps** [comment]
@kennyweiss , it seems `AXOM_GPUCC` might be unnecessary because all the uses we have found for it were better (more correctly) addressed by testing against `AXOM_USE_GPU`.  (See MR #1100.)  Those fixes came from Alan Dayton, who was trying to compile a complex code system (here reduced to essential details):

* Main code calls into libs S, T, Axom
* Libs S and T each call into Axom
* Main code has GPU turned on, but libs S and T can't compile with GPU on
* Alan wants to turn on GPU for Axom, but continues to have compilation failures.  I think that is partly because he's using a combination of compilers Axom doesn't test.

To get things to even compile, Alan had to turn off GPU in Axom.  `AXOM_USE_GPU` is the proper knob for that.  Using `AXOM_GPUCC` wasn't working.

There may be a situation where the code should test for the nvcc or hip compiler separately from the user's intent to turn on GPU support.  However, I haven't seen that situation.  Hence this issue, to discuss it.

**Comment by agcapps** [comment]
As noted on a discussion in MR #1100 , it looks like we do need `AXOM_GPUCC`.  There are files that use Axom Core's Array, which should be host-compiled even on GPU builds: these will fail if we only guard on `AXOM_USE_GPU`.  And if Axom needs to be compiled CPU-only, but Axom Array gets used in a host code that is being compiled for GPU, only guarding on `AXOM_GPUCC` will not be sufficient.

**Comment by agcapps** [comment]
Closing as a mistake: we should not deprecate `AXOM_GPUCC`.
