### ISSUE TITLE
Compilation issues with rocm@5.6.0beta1

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#1131]
@tomstitt reported compilation issues with `rocm@5.6.0beta1` of the form:
```
[  9%] Building CXX object axom/core/CMakeFiles/core.dir/numerics/polynomial_solvers.cpp.o
In file included from <axom-40bb16e>/src/axom/core/numerics/polynomial_solvers.cpp:6:
<axom-40bb16e>/src/axom/core/../../axom/core/utilities/Utilities.hpp:43:8: error: unknown type name '__host__'
inline AXOM_HOST_DEVICE T abs(const T& x)
       ^
<axom-40bb16e>/src/axom/core/../../axom/core/Macros.hpp:62:28: note: expanded from macro 'AXOM_HOST_DEVICE'
  #define AXOM_HOST_DEVICE __host__ __device__
```

@tomstitt also noted that it works fine with previous versions of rocm, e.g. 5.4.3, 5.5.0, 5.5.1

**Comment by rhornung67** [comment]
rocm 5.6.0 will be installed on rzvernal and tioga this week (by 7/7/2023). Please report this issue if it appears with the released compiler, as well as any other issues, to the El Capitan CoE.

**Comment by bmhan12** [comment]
This was tested in PR #1122. A bug was found in CLI11, with a workaround and reproduce documented [here](https://rzlc.llnl.gov/jira/browse/ELCAP-400).
