### ISSUE TITLE
Output dimension permutation in sidre::View

### ISSUE THREAD

**Issue by corbett5** [LLNL/axom#115]
In GEOSX we have an multidimensional array class with similar functionality to the `RAJA::View` in that it can permute the layout of the data. As part of our integrated testing we compare our sidre restart files with a baseline and we use a common set of baselines across all our platforms. In order to compare results across platforms our comparison script needs to reorder the data to match the layout of the baseline. To do this it needs both the dimensions of the data and their permutations.

`View` lets you describe the data with a shape and in my first pass I tried to hijack the shape to also include the permutation. I didn't realize that when you describe the data using the shape `View` calculates the number of entries for you as well so this doesn't work. One solution would be to add a method `View* apply( TypeID type, IndexType num_elems, int ndims, IndexType* shape )` where `num_elems` is used to override the number of values calculated from the shape. However this seems pretty hackish to me so I propose adding a new member `std::vector<IndexType> m_permutation` and method `View* apply( TypeID type, int ndims, IndexType* shape, IndexType* permutation )`.

**Comment by rhornung67** [comment]
will reopen if it comes up again
