### ISSUE TITLE
Bug in our sparsehash setup

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#12]
In our sparsehash setup, we have the following:

https://github.com/LLNL/axom/blob/9c6ebdcf475da4d1ba9d574ac26c2c6feec3d2dc/src/thirdparty/CMakeLists.txt#L128-L134

This errors out for ``gcc@8.1+`` when Fortran in not enabled with the following message:

```cmake
CMake Error at cmake/blt/cmake/BLTPrivateMacros.cmake:230 (target_link_libraries):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:Fortran>

  $<COMPILE_LANGUAGE:...> Unknown language.
```

**Comment by kennyweiss** [comment]
@corbett5 -- I assigned this one to you since you have the same logic in PR #4

**Comment by kennyweiss** [comment]
This prevented us from adding gcc@8 to our CI plan in #11

**Comment by rhornung67** [comment]
@corbett5 please let me know when this is fixed and I will enable gcc8 CI builds.
