### ISSUE TITLE
Tet hex volume of intersection bug

### ISSUE THREAD

**Issue by adayton1** [LLNL/axom#1206]
Axom's intersection_volume method seems to give the wrong answer for the following hexahedron and tetrahedron. This occurs on a CTS-1 machine with the intel 2022.1.0 compiler.

Hexahedron coordinates:
0, -12.1295, -33.6323
0, -12.2774, -33.6323
0.185429, -12.276, -33.6323
0.183195, -12.1281, -33.6323
0, -12.1295, -33.5186
0, -12.2774, -33.5186
0.185429, -12.276, -33.5186
0.183195, -12.1281, -33.5186

Tetrahedron coordinates:
0.0774795, -11.3217, -33.5237
0.482086, -12.283, -33.5237
-0.503954, -12.216, -33.5237
0.0368068, -12.1403, -33.4339

Computed intersection volume: 0
Expected intersection volume 0.000115679984

**Comment by adayton1** [comment]
I did some experimenting, and I found out the tetrahedron's signed volume is negative. When I set the checkSign parameter to true, the issue seems to be resolved.

**Comment by adayton1** [comment]
Thanks for looking into it as well, @bmhan12! I'm wondering if the checkSign flag should be set to true by default, since that seems to be safer.

**Comment by adayton1** [comment]
BoundingBox defaults to a safer option over performance: https://github.com/LLNL/axom/blob/develop/src/axom/primal/geometry/BoundingBox.hpp#L119

**Comment by kennyweiss** [comment]
Thanks @bmhan12 -- that works for me!

@adayton1 w/ #1212, assuming you have an array of `primal::Tetrahedron` you should be able to add something like:
```cpp
for(auto& tet : mesh_tetrahedra_array)
{
  tet.checkAndFixOrientation();
}
```
to fix any tets w/ negative orientations in your mesh before setting up the intersections. Does this work for your use case?

**Comment by adayton1** [comment]
> Thanks @bmhan12 -- that works for me!
> 
> @adayton1 w/ #1212, assuming you have an array of `primal::Tetrahedron` you should be able to add something like:
> 
> ```c++
> for(auto& tet : mesh_tetrahedra_array)
> {
>   tet.checkAndFixOrientation();
> }
> ```
> 
> to fix any tets w/ negative orientations in your mesh before setting up the intersections. Does this work for your use case?

That will work perfectly! Thanks!

**Comment by rhornung67** [comment]
@bmhan12 please check that this is resolved and alan's test data has been added to our tests. If so, please close this issue.
