### ISSUE TITLE
Quest point-in-cell timing

### ISSUE THREAD

**Issue by agcapps** [LLNL/axom#1222]
The `quest_point_in_cell_mfem` unit test release is slower than debug.  There may be a good reason for this; noting here for possible investigation.  Is it possible the Debug build is doing less work?

|Platform|Debug|Release|
|---|---|---|
|Win10 MSVC|28.6s|50.5s|
|TOSS4 Clang 14|2.7s|19.1s|
|BlueOS XLClang + CUDA|3.5s|20.1s|

**Comment by kennyweiss** [comment]
Thanks @agcapps -- if the test runtime in release builds is too long, we can reduce the resolution and/or number of query points.
