### ISSUE TITLE
Include <cstdint> for higher GCC versions

### ISSUE THREAD

**Issue by chapman39** [LLNL/axom#1272]
Newer versions of GCC require including `cstdint` explicitly in order to use `std::uint32_t` and similar types. It will need to be added to this file:

https://github.com/LLNL/axom/blob/develop/src/axom/core/utilities/nvtx/interface.hpp

I can create a PR for this soon.

This was hit by mfem recently as well: https://github.com/mfem/mfem/commit/19f30e814dc2846dd5ab8e827477d3da34b35d8d

**Comment by kennyweiss** [comment]
Thanks @chapman39 -- do you know which version of `gcc` triggers this error?
