### ISSUE TITLE
Need parallel stable sort algorithm on the GPU

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#132]
Currently construction of the BVH sorts the supplied bounding boxes on the CPU by default. Optionally, we can compile with CUB and use CUB's sorting routines, but, that can potentially lead to device linking issues due to an NVIDIA bug. 

There has been some discussion on providing a `sort` with RAJA (See https://github.com/LLNL/RAJA/issues/473).

In the meantime, we may want to write our own or use something else like Thrust's stable_sort if that is still available or  https://moderngpu.github.io/mergesort.html

**Comment by rhornung67** [comment]
Matt O'Brien has written a GPU sort for his code that we may want to consider.

**Comment by gzagaris** [comment]
@rhornung67 , yes, I have talked to him about this.

**Comment by rhornung67** [comment]
🥇

**Comment by cyrush** [comment]
Our Harvey Mudd students harvested Axom's GPU sort and ran into runtime issues that point to linking woes.  Are the linking issues described somewhere? Is it just the need for an omniscient device link step, or something more exotic? 

Ideally, It would be best to have a sort in RAJA.

**Comment by gzagaris** [comment]
@cyrush , this is documented here: https://lc.llnl.gov/confluence/pages/viewpage.action?pageId=134349041 (Issue #15). 

I was told that NVIDIA is aware of the issue, although there are no concrete plans for resolution to my knowledge.

What is peculiar about this is that it is only reproducible under certain linking conditions. For example, building Axom standalone there are no problems. However, linking Axom into another code will trigger the issue.

I agree that ideally this should be provided in RAJA -- it would it fit well along with the scan algorithms etc.

**Comment by gzagaris** [comment]
I chatted briefly with Jason Burmark about this today. It turns out that there may be a fix in `cuda/10.2` about this already.

**Comment by gzagaris** [comment]
The linking issue with CUB has been addressed in the latest drop of `cuda/10.1`. Also, Jason Burmark and others will be adding a sort primitive in RAJA, which, internally will use the appropriate backend, e.g., CUB, std::sort(), etc. In the meantime, we will use CUB and switch to RAJA when that's available.
