### ISSUE TITLE
Find polygon by intersecting tet with a plane

### ISSUE THREAD

**Issue by rhornung67** [LLNL/axom#1324]
@adayton1 requested a method to find the polygon resulting from the intersection of a tetrahedron with a plane. This would enable EL3D to use Axom to underpin their 2D ProE shaping. Typically, ALE3D intersects a tet with the plane z = 0, obtaining a 2D polygon (dropping the z coordinate), then computes the volume of intersection of that polygon with nearby quadrilaterals.

**Comment by BradWhitlock** [comment]
Wrote it, writing tests.
