### ISSUE TITLE
Failed device link for CUDA Shared libraries

### ISSUE THREAD

**Issue by mdavis36** [LLNL/axom#1355]
As a side effect to needing newer capabilities in other libraries Spheral is forced to update Axom as a part of our port to the GPU, when updating to Axom 0.9.0 we get a strange linker error whilst building a cuda shared library with axom as a dependency:

```
Consolidate compiler generated dependencies of target Spheral_CXX
Building CUDA object src/CMakeFiles/Spheral_CXX.dir/spheralCXX.cc.o
Linking CUDA device code CMakeFiles/Spheral_CXX.dir/cmake_device_link.o
g++: fatal error: cannot specify -o with -c, -S or -E with multiple files
compilation terminated.
```

We are building axom, raja and umpire through spack v0.22:

```
axom@0.9.0 ~shared +cuda +mpi +hdf5 -lua -examples -python -fortran
raja@2024.02.0 +cuda cuda_arch=70', when='+cuda
conduit@0.9.1 +shared +mpi +hdf5 -test ~parmetis
```

This was not an issue with axom 0.7.0. which we are currently using. I'm pretty sure this also worked with axom@0.8.1. It also is not an issue with static cuda library builds, but we unfortunately need shared.

My inclination is that this might be a BLT or CMake related issue with how the axom target is being used for a cmake, shared cuda library.

**Comment by bmhan12** [comment]
Not sure if this is relevant to folks, but I have seen Umpire have a static requirement to build with cuda (maybe that static requirement flows down to the cuda dependency?):
https://github.com/LLNL/radiuss-spack-configs/blob/037ee671622bd3ec2ff955ced356b59dc96fec58/packages/umpire/package.py#L284-L286

**Comment by mdavis36** [comment]
We are building Spheral_CXX target as shared, we are a C++ code with a python only interface essentially, so our C++ / CUDA library needs to be built shared so all of our python modules can point to the same instance at runtime. We've been building and linking our libraries with NVCC in this way for quite a long time in preparation for the GPU port. This issue only showed up after updating to axom 0.9.0.

**Comment by white238** [comment]
Turned out the fix was related to setting the `cmake_minimum_required` to greater than 3.14 plus cuda.

This needs to be further investigated and/or have a check added to BLT to guard against whatever combination causes this failure state but they are no longer blocked.
