### ISSUE TITLE
Consider a single pass algorithm for the BVH::find() when possible

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#136]
`BVH::find()` is currently implemented as a two-pass algorithm. In the first pass, the total number of candidates are found, an buffer to store the candidates is allocated and then, in a second pass, the candidates buffer is populated.

Alternatively, we could heuristically allocate a buffer that is "sufficiently" large, e.g., half the total number of bins, and, if possible, populate the candidates buffer in a single pass, otherwise, resort to a the two-pass algorithm.

This could be especially important for iterative algorithms, where the BVH is invoked at every time-step, where for example, we can make an educated "guess" for the total number of candidates based on the results from the previous cycle.

**Comment by kennyweiss** [comment]
This has been partially addressed by the `BVH::getTraverser()` function.
For some use cases, e.g. MeshTester and/or Tribol's binning query, users would likely want a 2-pass algorithm for better load balancing.

Users can pass in custom lambdas when necessary, e.g. for `SignedDistance`.
