### ISSUE TITLE
Primal Vector namespace

### ISSUE THREAD

**Issue by BradWhitlock** [LLNL/axom#1384]
Vector is co-located with other geometry classes in axom/src/axom/primal/geometry but is in the **axom::primal** namespace whereas other classes are in **axom::primal::geometry**. What's the reason for this? It just struck me as a little strange since they are co-located.

* Should Vector also be in axom::primal::geometry? Are there legacy reasons for its current namespace location?
* This would be a breaking change for users
* This is very minor nitpick

**Comment by bmhan12** [comment]
I think all of the classes in the axom/src/axom/primal/geometry directory (as well axom/src/axom/primal/operators) as are in the **axom::primal** namespace. I think the subfolders in primal are just for organization, but everything is in the axom::primal namespace.

**Comment by BradWhitlock** [comment]
On closer inspection, it looks like you're right. Hm. I must have had some other error someplace that made it me think there was an extra geometry namespace. I'll close this.
