### ISSUE TITLE
Move Sidre collections to core

### ISSUE THREAD

**Issue by rhornung67** [LLNL/axom#1397]
Sidre's map and item collections can be used in other components:

- https://github.com/LLNL/axom/blob/develop/src/axom/sidre/core/MapCollection.hpp
- https://github.com/LLNL/axom/blob/develop/src/axom/sidre/core/ItemCollection.hpp

Since those classes are not specific to Axom and have no other Axom dependencies, it makes sense to move them to the Axom core component.

**Comment by rhornung67** [comment]
Potential issue with get name function, which is not generic

**Comment by nselliott** [comment]
The one Axom dependency that exists in these collection classes is slic, as there are a few assertions and one warning.  Removing them would have no effect on the functionality, but would increase risk in the case that calls are made that would have triggered the assertions or warning.  Is there a reasonable alternative to slic in this case?

**Comment by bmhan12** [comment]
In core, at least for assertions, the current way is to replace `SLIC_ASSERT` with `assert()` to not have the dependency between core and slic: https://github.com/search?q=repo%3ALLNL%2Faxom+%22assert%22+path%3Asrc%2Faxom%2Fcore%2F*&type=code

**Comment by nselliott** [comment]
Thanks @bmhan12, I can definitely do that for the assertions.  For the warning, I suppose I should write a std::cerr message like in axom::Array since I don't have access to the Logger.
