### ISSUE TITLE
Invalid pointer error for static built Axom linked into a separate shared library

### ISSUE THREAD

**Issue by ldowen** [LLNL/axom#1408]
I get a `free(): invalid pointer` error on this static variable:
https://github.com/LLNL/axom/blob/5374375a1cb026642a774f43a109fb97ac87822e/src/axom/sidre/core/Group.hpp#L1933

This only occurs if our code is built as shared libraries but Axom is built as static libraries. If Axom is built as shared libraries or our code is built as a static library, we don't get this error. This was not an issue for version 0.7.0 when this static variable did not exist.

**Comment by cyrush** [comment]
@ldowen  thank you, does this happen when your program closes?

This sounds like a c++ static finalization issue.

**Comment by ldowen** [comment]
Ah right, I forgot to mention that: the error occurs when the program closes.
