### ISSUE TITLE
Check removeFile() return value

### ISSUE THREAD

**Issue by bmhan12** [LLNL/axom#1415]
Issue is opened from this [discussion](https://github.com/LLNL/axom/pull/1387#discussion_r1764403743).

- [x] Various [parts of the code](https://github.com/search?q=repo%3ALLNL%2Faxom%20removeFIle&type=code) call `removeFile`, but do not verify that the file has actually been deleted through the return code/checking if file stills exist. Warning, error, or at least some indication should be given to user if file deletion has failed.
- [x] Fix `removeFile` usage on Windows in `slic_macros.cpp` test case (from original discussion)

**Comment by kennyweiss** [comment]
Related: @agcapps noted in https://github.com/LLNL/axom/pull/1421 that `Unlink` on Windows only works when all file handles are closed.

**Comment by bmhan12** [comment]
Closed by #1424
