### ISSUE TITLE
Add caliper as an optional third party dependency 

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#142]
We should add  [caliper](https://github.com/llnl/caliper) as an optional third-party dependency to Axom.

In addition to our internal usage (e.g. in axom's examples), 
this would allow user codes that build with caliper to capture performance data within their calls to axom components.

We should also provide some simple macros to streamline adding annotations within Axom components, e.g.
```cpp
AXOM_ANNOTATE_BEGIN(<label>)
AXOM_ANNOTATE_END(<label>)
AXOM_ANNOTATE_SCOPE(<label>)
```

**Comment by rhornung67** [comment]
@kennyweiss has a PR nearing completion for this. We should have a follow up meeting to define how we want to use caliper in Axom.
