### ISSUE TITLE
Undefined Behavior flagged using closest point

### ISSUE THREAD

**Issue by bryujin** [LLNL/axom#1451]
Running ubsan on a TOSS4 CPU system flagged an error in Axom. It looks to me like it's pointing at m_executeOnGPU. I don't see where it's being initialized, so may be the issue.

The stack trace is:

0: /axom/0.10.0/include/axom/core/Array.hpp:1718:29: runtime error: load of value 99, which is not a valid value for type 'bool'
0:     #0 0x2ba2de8 in axom::Array<int, 1, (axom::MemorySpace)0>::setCapacity(int) /axom/0.10.0/include/axom/core/Array.hpp:1718:29
0:     #1 0x2ba2498 in axom::Array<int, 1, (axom::MemorySpace)0>::initialize(int, int, bool) /axom/0.10.0/include/axom/core/Array.hpp:1588:3
0:     #2 0x2ba1ae0 in axom::Array<int, 1, (axom::MemorySpace)0>::Array<1, (axom::MemorySpace)0, (void*)0>(int, int, int) /axom/0.10.0/include/axom/core/Array.hpp:1084:3
0:     #3 0x2ba1ae0 in void axom::spin::internal::linear_bvh::propagate_aabbs<axom::SEQ_EXEC, double, 2>(axom::spin::internal::linear_bvh::RadixTree<double, 2>&, int) /axom/0.10.0/include/axom/spin/internal/linear_bvh/build_radix_tree.hpp:554:23
0:     #4 0x899e456 in void axom::spin::internal::linear_bvh::build_radix_tree<axom::SEQ_EXEC, axom::ArrayView<axom::primal::BoundingBox<double, 2>, 1, (axom::MemorySpace)0>, double, 2>(axom::ArrayView<axom::primal::BoundingBox<double, 2>, 1, (axom::MemorySpace)0>, int, axom::primal::BoundingBox<double, 2>&, axom::spin::internal::linear_bvh::RadixTree<double, 2>&, double, int) /axom/core/../../axom/spin/internal/linear_bvh/build_radix_tree.hpp:641:3
0:     #5 0x899d980 in void axom::spin::policy::LinearBVH<double, 2, axom::SEQ_EXEC>::buildImpl<axom::ArrayView<axom::primal::BoundingBox<double, 2>, 1, (axom::MemorySpace)0>>(axom::ArrayView<axom::primal::BoundingBox<double, 2>, 1, (axom::MemorySpace)0>, int, double, int) /axom/core/../../axom/spin/policy/LinearBVH.hpp:230:3
0:     #6 0x899d6d9 in int axom::spin::BVH<2, axom::SEQ_EXEC, double, (axom::spin::BVHType)0>::initialize<axom::ArrayView<axom::primal::BoundingBox<double, 2>, 1, (axom::MemorySpace)0>>(axom::ArrayView<axom::primal::BoundingBox<double, 2>, 1, (axom::MemorySpace)0>, int) /axom/core/../../axom/spin/BVH.hpp:443:12
0:     #7 0x899d370 in axom::quest::internal::DistributedClosestPointExec<2, axom::SEQ_EXEC>::generateBVHTreeImpl(axom::spin::BVH<2, axom::SEQ_EXEC, double, (axom::spin::BVHType)0>*) /axom/core/../../axom/quest/detail/DistributedClosestPointImpl.hpp:959:23
0:     #8 0x899b9b1 in axom::quest::internal::DistributedClosestPointExec<2, axom::SEQ_EXEC>::generateBVHTree() /axom/core/../../axom/quest/detail/DistributedClosestPointImpl.hpp:706:12

**Comment by BradWhitlock** [comment]
This [merged PR](https://github.com/LLNL/axom/commit/f6b1f59a7e91494a61513c5cc9b36e95acbef305#diff-b56e5d0c915fba2c55829d2984a4cbb8180b1789c8c0967e5ca145723eb0d349) initializes _m_executeOnGPU_. I ran into that with valgrind on rzansel.

**Comment by rhornung67** [comment]
@BradWhitlock you beet me to it. I was just about to post a similar comment. Thanks.

**Comment by rhornung67** [comment]
User verified that @BradWhitlock PR merged earlier resolves the issue.
