### ISSUE TITLE
CLI11 warnings on BlueOS+CUDA.

### ISSUE THREAD

**Issue by BradWhitlock** [LLNL/axom#1457]
These warnings were reported by the Ares team and they would like them to be corrected. It looks like they are building on BlueOS with CUDA enabled.

/usr/gapps/bdiv/blueos_3_ppc64le_ib_p9/clang-ibm-16.0.6-cuda-11.8.0-gcc-11.2.1/axom/0.10.0-cuda/include/axom/CLI11.hpp(1001): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/usr/gapps/bdiv/blueos_3_ppc64le_ib_p9/clang-ibm-16.0.6-cuda-11.8.0-gcc-11.2.1/axom/0.10.0-cuda/include/axom/CLI11.hpp(1005): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

**Comment by rhornung67** [comment]
Should we update our version of CLI11? Maybe this is fixed in a newer version.

**Comment by white238** [comment]
It does seem to be fixed in the current CLI11:

https://github.com/CLIUtils/CLI11/blob/5a03ee58384ce18b6b3de5a2256e18f5ef103633/include/CLI/TypeTools.hpp#L190-L194
