### ISSUE TITLE
Add copy and move operators to axom's array classes

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#154]
Users of an array class would expect support for copying and moving operations, but our array class explicitly disables these:

https://github.com/LLNL/axom/blob/61cd97c5aad8c96fd5d3defe16f5f72667ee1b99/src/axom/core/Array.hpp#L488-L489

A tricky aspect of this might be related to the proper semantics for copying and moving sidre-based arrays.

See: 
* https://github.com/LLNL/axom/blob/develop/src/axom/core/Array.hpp
* https://github.com/LLNL/axom/blob/develop/src/axom/sidre/core/Array.hpp

**Comment by gzagaris** [comment]
@kennyweiss , I have concerns with making this change. 

This would allow users to pass objects around and make copies, which would not perform well and use the class in a way that they shouldn't.

Instead, I would be OK with having a `deepCopy()` function or method to do that. That way it is more explicit and users are consciously aware of what they are doing.

**Comment by kennyweiss** [comment]
@joshessman-llnl  -- I'm pretty sure you've resolved this issue. 
Could you please command and/or close?

**Comment by rhornung67** [comment]
No longer relevant.
