### ISSUE TITLE
Fix MPI+OpenMP tests on llnl's rzgenie machine

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#158]
LLNL's rzgenie machine recently changed its ``mpibind`` policy, which is causing our ``MPI``+``OpenMP`` CI tests to fail there.  Specifically, ``sidre_lulesh`` and ``slam_lulesh``.

The fix appears to be adding ``--mpibind=off`` to the slurm launch command (either ``salloc`` or ``srun``).

**Comment by white238** [comment]
I have added --mpibind=off to bamboo but i would like to talk to LC about if this really is the "fix" because if the users don't know to do that then it just looks like our code is broken.

**Comment by rhornung67** [comment]
@white238 I appreciate that, but there was an email from LC about this. If users don't pay attention, I'm not sure how we can avoid this sort of potential issue.

**Comment by kennyweiss** [comment]
@white238 -- I think this has been resolved (at least to the extent that it will be resolved).
Can you please comment and/or close this?
