### ISSUE TITLE
Azure GCC jobs take 3-4 times 

### ISSUE THREAD

**Issue by white238** [LLNL/axom#168]
I haven't looked into this at all just noticed it and don't want to forget.

<img width="1081" alt="AxomAzureTimes" src="https://user-images.githubusercontent.com/595301/74761326-b2ce6500-5230-11ea-9f05-0eb37e1537eb.png">

**Comment by kennyweiss** [comment]
I think it was due to the ``sidre_lulesh`` problem, which was resolved in #167.

Here is the most recent run:
![image](https://user-images.githubusercontent.com/5626552/74879254-96f4bd00-531d-11ea-8510-08ff78e9ba1d.png)

See: https://dev.azure.com/axom/axom/_build/results?buildId=935&view=results

**Comment by kennyweiss** [comment]
Closing, but please reopen if you still see the problem.
