### ISSUE TITLE
cxxabi is not found when compling with clang++ -stdlib=libc++

### ISSUE THREAD

**Issue by brunner6** [LLNL/axom#179]
In the file `axom/slic/internal/stacktrace.cpp`, there is a include `#include <cxxabi.h>` which is a GCC specific extension.  It is already protected against for Microsoft compilers.  It also should be protected against for using Clang's libc++.

**Comment by gzagaris** [comment]
Thanks @brunner6 , we should properly guard the use of GCC extensions if it is unavoidable. I'll take a look and push a fix.

**Comment by brunner6** [comment]
Here's one patch that I haven't figure out how to test yet.  I can't figure out how to test with uberenv/spack/etc.

`+++ b/src/axom/slic/internal/stacktrace.cpp
@@ -13,7 +13,10 @@
   #include <DbgHelp.h>
 #else
   #include <execinfo.h> // for backtrace()
-  #include <cxxabi.h>   // for abi::__cxa_demangle
+  #include <ciso646>
+  #if !defined(_LIBCPP_VERSION)
+     #include <cxxabi.h>   // for abi::__cxa_demangle
+  #endif
 #endif
 
 constexpr int MAX_FRAMES = 25;
@@ -122,9 +125,13 @@ std::string demangle( char* backtraceString, int frame )
     *returnOffset = 0;
     ++returnOffset;
 
-    int status;
+    int status = false;
+#if !defined(_LIBCPP_VERSION)
     char* realName = abi::__cxa_demangle( mangledName, nullptr, nullptr,
                                           &status );
+#else
+    char* realName = mangledName;
+#endif
 
     // if demangling is successful, output the demangled function name
     if (status == 0)`

**Comment by gzagaris** [comment]
> Here's one patch that I haven't figure out how to test yet

Thanks for the patch (feel free to push a branch and make a PR too if you've made changes). 

What was the trigger for submitting this issue? Was it by inspection of the code? or did you get a compilation failure? If it was the latter, were you building on an LC platform or locally? Could you share your host-config or CMakeCache.txt file?

**Comment by kennyweiss** [comment]
We have a blt ``host-config`` for ``clang + libc++``, which we added for one of @brunner6's libraries.  

The relevant config lines are here:
https://github.com/LLNL/blt/blob/e5564c491cb9032e529768ffc1e7b2696659da92/host-configs/llnl/toss_3_x86_64_ib/clang%404.0.0-libcxx.cmake#L35-L37

Perhaps we should add a similar config to Axom's CI ?

**Comment by brunner6** [comment]
The trigger was trying to build Axom with our compilers.  It gets a little tricky, since all C++ needs the libc++ or not, kull has compiler wrapper scripts to ensure this flag is always on, independent of each library's build systems.  (It is really hard to ensure that all TPLs respect the flags you want to use.)

Here is our cmake line:
```
cmake /usr/WS1/brunner6/buildClang/libraries/Axom-v0.3.3/src -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/dnta/kull/developers/tools/compilers/mvapich2-2.3/clang-9.0.0/clang -DMPI_C_COMPILER=/usr/dnta/kull/developers/tools/compilers/mvapich2-2.3/clang-9.0.0/mpicc -DCMAKE_C_FLAGS_RELEASE=-fPIC   -DLINUX -DLinux -DLinux64  -O3 -g1 -fPIC   -DLINUX -DLinux -DLinux64   -DMPI_C_COMPILE_FLAGS=-fPIC   -DLINUX -DLinux -DLinux64  -O3 -g1 -fPIC   -DUSE_MPI -DMPICH_SKIP_MPICXX  -DLINUX -DLinux -DLinux64  -DCMAKE_Fortran_COMPILER=/usr/tce/packages/gcc/gcc-8.1.0/bin/gfortran -DMPI_Fortran_COMPILER=/usr/dnta/kull/developers/tools/compilers/mvapich2-2.3/clang-9.0.0/mpif90 -DCMAKE_Fortran_FLAGS_RELEASE=-fPIC -ffree-line-length-none -ffixed-line-length-none   -DLINUX -DLinux -DLinux64  -O3 -g1 -fPIC -ffree-line-length-none -ffixed-line-length-none   -DLINUX -DLinux -DLinux64  -DMPI_Fortran_COMPILE_FLAGS=-fPIC -ffree-line-length-none -ffixed-line-length-none   -DLINUX -DLinux -DLinux64  -O3 -g1 -fPIC -ffree-line-length-none -ffixed-line-length-none   -DUSE_MPI -DMPICH_SKIP_MPICXX  -DLINUX -DLinux -DLinux64  -DCMAKE_CXX_COMPILER=/usr/dnta/kull/developers/tools/compilers/mvapich2-2.3/clang-9.0.0/clang++ -DMPI_CXX_COMPILER=/usr/dnta/kull/developers/tools/compilers/mvapich2-2.3/clang-9.0.0/mpicxx -DCMAKE_CXX_FLAGS_RELEASE=-fPIC   -DLINUX -DLinux -DLinux64  -O3 -g1 -fPIC  -Wno-undefined-var-template   -DLINUX -DLinux -DLinux64  -I/usr/tce/packages/mvapich2/mvapich2-2.3-clang-9.0.0/include -I/usr/WS1/brunner6/buildClang/include/  -DMPI_CXX_COMPILE_FLAGS=-fPIC   -DLINUX -DLinux -DLinux64  -O3 -g1 -fPIC  -Wno-undefined-var-template   -DUSE_MPI -DMPICH_SKIP_MPICXX  -DLINUX -DLinux -DLinux64  -I/usr/tce/packages/mvapich2/mvapich2-2.3-clang-9.0.0/include -I/usr/WS1/brunner6/buildClang/include/  -DENABLE_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr/WS1/brunner6/buildClang -DCMAKE_BUILD_PREFIX=/usr/WS1/brunner6/buildClang/libraries/Axom-v0.3.3-build -DENABLE_EXAMPLES=OFF -DENABLE_MPI=ON -DENABLE_FORTRAN=OFF -DENABLE_PYTHON=OFF -DENABLE_DOCS=OFF -DENABLE_SHROUD=OFF -DHDF5_DIR=/usr/WS1/brunner6/buildClang -DHDF5_INCLUDE_DIRS=/usr/WS1/brunner6/buildClang/include -DCONDUIT_DIR=/usr/WS1/brunner6/buildClang -DBOOST_DIR=/usr/WS1/brunner6/buildClang -DCMAKE_VERBOSE_MAKEFILE=ON
```

Our compiler wrappers look like this:

```
#!/bin/sh

GCC_TOOLCHAIN="--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.1.0"
exec /usr/tce/packages/clang/clang-9.0.0/bin/clang++ $GCC_TOOLCHAIN -std=c++14 -stdlib=libc++ "$@"

```

**Comment by brunner6** [comment]
I tried pushing my branch, and got denied.  Do I need to fork the repo, and do a PR from there?

The patch I sent compiles in KULL with the cmake line above.  I don't have a way to test it in stand-alone axom, thought.

**Comment by gzagaris** [comment]
@brunner6 , I sent you an invite to join. You should be able to push your branch afterwards. Otherwise, yes, creating a PR from your own fork is the typical github workflow.
