### ISSUE TITLE
Add toss3 TPL and host-config for clang with `libc++`

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#183]
A user recently experienced an issue with a clang-based configuration that used ``libc++`` instead of ``glibc`` as its standard library.

We should add a host-config + TPL build on LLNL's ``toss3`` platform for this configuration.

Links:
* Similar host-config in blt -- https://github.com/LLNL/blt/blob/develop/host-configs/llnl/toss_3_x86_64_ib/clang@4.0.0-libcxx.cmake
* Related issues and PRs: #179, #180

**Comment by rhornung67** [comment]
will re-open if user issue comes up again
