### ISSUE TITLE
blueos9 host-config for XL+nvcc

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#190]
A user requested an XL+nvcc configuration on LLNL's ``blueos`` platform.

When they tried to set it up themselves, they found a possible compilation error.

**Comment by rhornung67** [comment]
FWIW, here’s one of the RAJA test build scripts:  https://github.com/LLNL/RAJA/blob/develop/scripts/lc-builds/blueos_nvcc10_xl-2019.12.23.sh

And the associated host-config file: https://github.com/LLNL/RAJA/blob/develop/host-configs/lc-builds/blueos/nvcc_xl_2019_X.cmake


--Rich

**Comment by kennyweiss** [comment]
The ``XL+nvcc`` configuration appears to work without any fixes. See #191.

The user's compilation error appears to be due to their use of a flag in their ``CMAKE_CUDA_FLAGS`` which ``axom`` doesn't use:
```
--expt-relaxed-constexpr
```

This generated the following error:
```
Internal Compiler Error (codegen): "there was an error in verifying the lgenfe output!"
```

Posting it here as a comment in case we decide to use this in the future.

**Comment by mdavis36** [comment]
I ran into this issue with `axom@0.9.0` with `gcc@8.3.1` and `cuda@11.1.1`. Removing `--expt-relaxed-constexpr` did resolve the problem but I don't understand why it causes this error to throw in the first place.
