### ISSUE TITLE
Simplify and streamline Sidre I/O with external data

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#198]
This issue came up in PR #193 

Currently when Sidre holds external data, a 3-step process is required when reading back the data, namely:

1. Load the sidre view
2. Parse the tree, allocate external data pointers for the external view and set the external pointers
3. Load the external data

Although this provides great flexibility in applications for certain scenarios that is needed, it can be counterintuitive for simpler cases.

One comprise could be to provide a fast path where the Sidre will read back the data and assume ownership of the data that is external. Possible solutions are to add an option to `sidre::IOManager::read()` or add another method `sidre::IOManager::readAll()` or something like that.

See `axom/sidre/examples/sidre_external_array.cpp`, which illustrates this use case.

**Comment by kennyweiss** [comment]
Looks like this was covered in #193
