### ISSUE TITLE
CI Checks report Pass while CI is only partially finished

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#201]
I observed that our CI checks were reporting as passed while some of the CI jobs were still running (see screen shot below).

This would allow a PR to be merged without ensuring that all CI jobs are passing.

![Screen Shot 2020-03-28 at 10 47 32 PM](https://user-images.githubusercontent.com/450194/77842477-73583a00-7147-11ea-9f27-de27e232a2b4.png)

**Comment by white238** [comment]
We were missing the individual status checkboxes.  It seems to be fixed now.
