### ISSUE TITLE
List individual CI jobs as CI Checks

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#202]
Currently our CI Checks include a single check `LLNL.axom` that holds an aggregate status of all the individual CI jobs on Azure. Consequently, in order to figure what exactly has failed, we are required to click on the "Details" link and go the "Azure" website in order to what is failing.

This issue proposes having individual CI checks corresponding to each test platform. This would more clearly indicate the status of the code on each platform within the PR without requiring to navigate into azure.

We may also want to consider having separate CI checks for the build phase and the test phase on each platform that we can tell right away whether tests are failing or the code is broken.

**Comment by keithhealy** [comment]
I don't have access to the System menu for this repo.  George, can you go to Settings->Branches->Branch Protection Rules and tell me what the current rules look like?

**Comment by gzagaris** [comment]
@keithhealy there are branch protection rules for `develop` and `master` . The section "Require status checks to pass before merging" lists `LLNL.axom`. I think what we want there is to have a listing of each individual job as opposed to a single entry that holds the aggregate status of each job. Does that make sense? Is that possible?

**Comment by gzagaris** [comment]
@keithhealy perhaps it would be better to test things out on a private fork to minimize any potential disruption.

**Comment by gzagaris** [comment]
Here is a screenshot of the relevant section:

![Screen Shot 2020-04-03 at 9 15 03 AM](https://user-images.githubusercontent.com/450194/78382415-ae190280-758b-11ea-9854-4438fc256e71.png)

**Comment by keithhealy** [comment]
Yes I've tried to duplicate in my fork and this is what I see:
![image](https://user-images.githubusercontent.com/50376825/78383153-c6d5e800-758c-11ea-839e-f541dac7a4b2.png)

**Comment by gzagaris** [comment]
Awesome! How is this list populated? I am assuming you are using the same `azure-pipelines.yml`.  Perhaps, it depends on how your `keithhealy.axom` project on Azure is setup?

**Comment by gzagaris** [comment]
May you have defined separate pipelines on Azure for each job?

**Comment by keithhealy** [comment]
Same yaml.  I set up the pipeline by just pointing to the repo on Github.  I can't think of anything different with the fork other than the added clang compilers.  And I don't think that's important. 
Can you try creating a new branch protection rule (without saving)?  Do you only see the llnl.axom item when you do?

**Comment by gzagaris** [comment]
> Can you try creating a new branch protection rule (without saving)? Do you only see the llnl.axom item when you do?

Yes -- I only see `llnl.axom` when I do that.

**Comment by gzagaris** [comment]
Maybe it's a matter of creating the different statuses: https://developer.github.com/v3/repos/statuses/#create-a-status

**Comment by keithhealy** [comment]
No.  I created the pipeline and ran it.  After it ran I was able to create the rule with all the individual items present.  Before the first run there were no items present.  So it appears that Azure tells Github what checks are available.
I'll play around with my fork and see if I can figure out what's different.

**Comment by gzagaris** [comment]
@keithhealy -- this appears to be working in some of the recent PRs. Did you fix something?

**Comment by keithhealy** [comment]
I just created a new pipeline and pointed it at the Axom repo.  Github seems to set the check values when pipelines are run.  So I didn't really fix anything. Just got Github to reset the check values.  Hopefully it will stay this way.

**Comment by gzagaris** [comment]
Ok, thanks -- it looks like that did the trick.
