### ISSUE TITLE
Consider making IOManager::read() and IOManager::write() MPI collective operations

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#203]
IOManager::read() and IOManager::write() are not collective operations. However, application may want to call those methods in a collective mode. Moreover, when using SCR the behavior is different and these methods are collective[1]. 

Should we make these methods collective to be consistent with SCR?

Should we have an option or corresponding method to have a collective flavor for these methods. For example, `IOManager::readAll()` and `IOManager::writeAll()` ?

[1] email discussion with @cyrush on 3/28

**Comment by nselliott** [comment]
They are already collective operations.  write() will hang in MPI_Barrier() if not called collectively.  read() might pass through if called non-collectively, but behavior will be wrong.  If we need to add barriers at the end of each and/or add some error-checking, that's fine.

**Comment by gzagaris** [comment]
> They are already collective operations. write() will hang in MPI_Barrier() if not called collectively. read() might pass through if called non-collectively, but behavior will be wrong. If we need to add barriers at the end of each and/or add some error-checking, that's fine.

Thanks for clarifying @nselliott -- I think adding barriers at the end and documenting that these are collective operations will go a long way and be elucidating from a usability standpoint.

**Comment by cyrush** [comment]
to summarize: they always need to be called collectively - that is all ranks need to participate in the calls. (nothing has changed there), 

but: 
- the write case might be missing a barrier at the end
- or the read might need a barrier at the beginning
- or we might need to tell folks to barrier in-between if it matters for their case
