### ISSUE TITLE
Priority-based BVH Traversal

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#204]
The present implementation of the BVH is using a stack to traverse the list of candidates. 

However, for certain queries, it is advantageous to traverse the candidates in a sorted fashion, i.e., closest-to-farthest (e.g., for a line-out) or may want just the closest candidates (e.g., signed-distance, PDV, etc.). For these type of geometric queries, using a priority queue (instead of a stack) would offer performance advantage as it would ensure that the candidate list is sorted by construction and nullify the need to sort the list of candidates in a separate step (kernel invocation).

**Comment by kennyweiss** [comment]
@kanye-quest -- Is this covered by https://github.com/LLNL/axom/pull/652 ? 
If not, is this issue still relevant/necessary?

**Comment by kanye-quest** [comment]
I think this might be relevant from an investigational standpoint, but I'm not sure of the performance advantages over our current greedy traversal to converge on the closest candidate.

**Comment by kennyweiss** [comment]
Closing for now based on #652
This sounds like an interesting idea to pursue in the future, if time permits.
