### ISSUE TITLE
Support BVH Ray Queries on Axisymetric Domains

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#205]
For certain applications, the symmetry of the problem is taken into account and the domain of interest is represented using a 2D Axisymmetric mesh. Consequently, the mesh is physically in 2D rz-coordinate system, but, all the physics take into account the 3D revolved model about an axis (e.g., the x-axis)

For these type of applications, the ray inputs are in 3D, but, the BVH is in 2D. Finding the list of candidates amounts to computing the intersection of a ray with a revolved bounding box around a specified axis of revolution.

**Comment by kennyweiss** [comment]
Let's wait for a concrete use case before developing this as there can be a balance between Axom's responsibilities and the host code's responsibilities.
