### ISSUE TITLE
BVH support for find-nearest type of queries

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#206]
The BVH currently supports two types of queries:

- finding candidates that **contain** a set of points
- finding candidates that **intersect** a set of rays

We also need to support
- finding candidates that are **nearest** to a set of points

This is needed for porting the SignedDistance query in Quest to the GPUs.

**Comment by kennyweiss** [comment]
Note: We should investigate if this is still needed.
Based on a comment in #207, it sounds like this might already be supported by our refactored BVH tree.

**Comment by kanye-quest** [comment]
This is supported indirectly by the device traversal API - `SignedDistance` defines a custom traversal predicate that updates the current-closest candidates. However, this isn't implemented in the `BVH` class directly.

Are there other use cases that would desire a `findClosestCandidates()`-like function?

**Comment by kennyweiss** [comment]
Closing for now and can reopen as necessary.
The current approach is to write custom lambdas for `LeafAction` and `Predicate` testing.
