### ISSUE TITLE
Upgrade built-in FMT library

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#210]
We are currently using version 5.3 of the built-in ``fmt`` library (from ~12/2018).
There have been numerous updates and fixes, see: https://github.com/fmtlib/fmt/blob/master/ChangeLog.rst

This might resolve some warnings that @agcapps is noticing in his Windows build.

**Comment by white238** [comment]
I got another customer asking for us to update fmt to the newest (also there is this related issue #237).

If no one has objections, I am going to try to tackle this in the near future.

**Comment by cyrush** [comment]
conduit has a newer version if that helps at all, you could pull its source, search and replace would allow you to namespace for axom, since that surgery was done with a unique name for conduit
