### ISSUE TITLE
Free up space on Azure DevOps space

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#214]
Our CI jobs have been failing since 4/2 due to 

> [error] No space left on device

It seems that we need to free up space within our Azure plans.

- [ ] @white238 is investigating an option to clean the build space after each pipeline.
  
- [x] We should also look into reducing the number of retained jobs (or number of days to retain jobs).

- [ ] Reduce the number of compilers that we are testing.
       Our linux plan is currently testing gcc 6, 7 and 8 and clang 4, 5 and 6.

Possibly helpful links:
* https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&viewFallbackFrom=vsts&tabs=schema%2Cparameter-schema#job
* https://developercommunity.visualstudio.com/content/problem/350899/azure-devops-build-fails-with-error-enospc-no-spac.html
* https://github.com/LLNL/axom/blob/38f974aaecb7ffcb2889781d31846504b01c53c2/azure-pipelines.yml#L70

**Comment by rhornung67** [comment]
due to....what? The suspense is killing me! :-)

**Comment by kennyweiss** [comment]
Working on it... the ticket got submitted early...

**Comment by kennyweiss** [comment]
@rhornung67 -- You appear to be the only person with the ability to changes settings on this page:
https://dev.azure.com/axom/axom/_settings/testmanagement

Can you change them to 20 days for both automated and manual builds?

**Comment by rhornung67** [comment]
@kennyweiss done!

**Comment by kennyweiss** [comment]
@white238   -- it looks like this was resolved in #215. Can you please confirm and close?
