### ISSUE TITLE
Possible problem with gcc-6 docker image

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#216]
The `gcc-6` build has been failing with an error message indicating that it is out of space (see #215)

Looking at the docker images, the `gcc-6` image is close to 4GB while the other compilers are closer to 1GB. See: https://hub.docker.com/r/axom/tpls/tags

It looks like the `gcc-6` docker image might be using `gfortran-7`.

https://github.com/LLNL/axom/blob/38f974aaecb7ffcb2889781d31846504b01c53c2/scripts/docker/dockerfile_gcc-6#L1-L6

To resolve this, we might need to fix and rebuild the `axom/tpl/gcc-6` image against `gfortran-6`.

**Comment by kennyweiss** [comment]
In the short term, I'd recommend disabling the ``gcc-6`` CI plan.

**Comment by kennyweiss** [comment]
@davidbeckingsale, @keithhealy  -- Is there any reason that the docker `axom/compiler` images for `gcc` do not all contain `gfortran` ?

It looks like ``gcc-5`` does -- https://github.com/LLNL/axom-docker/blob/master/gcc-5/Dockerfile
But the others do not.

**Comment by white238** [comment]
This was disabled a while ago.
