### ISSUE TITLE
Add support for pointing Axom to an external CUB instead of always using the one that may be provided with RAJA

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#224]
The BVH currently uses the CUB that is provided with RAJA when compiled with CUDA and executed on the device.

However, RAJA may be compiled with an external CUB, in which case, we need to make sure that Axom is using the same CUB as well.

**Comment by gzagaris** [comment]
Note: In the future, when we switch to using RAJA's `sort()` functionality this would probably not be needed since we wouldn't be using CUB directly in Axom.

**Comment by kennyweiss** [comment]
Axom imports cub from RAJA's exports.
We use `RAJA:sort()` rather than the direct sort from `cub`.

Closing for now and will reopen if necessary.
