### ISSUE TITLE
Cuda Arch consistency

### ISSUE THREAD

**Issue by mclarsen** [LLNL/axom#236]
Re: #235 

@white238 @kennyweiss @rhornung67 

 Weird we all run into this at the same time. The RAJA package(and many others) does not respect the cuda arch in spack. I just fixed this inside my uber and created a pull request in mainline spack:

https://github.com/spack/spack/pull/16377

Two notes, the spack package must inherit from CudaPackage, and when it does you can pass the cuda arch in as variant and set the right cmake variable. It would be nice if there was a standard BLT variable like `BLT_CUDA_ARCH`  that we  could set. It would also be nice if the installation told downstream dependencies about what architecture it was using. Thoughts?

**Comment by mclarsen** [comment]
Another thought: we are all maintaining similar sets of spack packages that don't exist in their current for in main spack. Is there a way we can consolidate this maintenance? I know we (Ascent) are very afraid of new spack, so keeping things separate while contributing back upstream is good.

**Comment by rhornung67** [comment]
@mclarsen we are aware of this problem. I think @white238 figured it out on the axom end yesterday -- hardcoding the wrong cuda arch level in our spack package or something like that. He was working on a fix. I think if we all had the same mechanism for handling this. @white238 @cyrush @kennyweiss , etc. will have to weigh in with their thoughts.

**Comment by gzagaris** [comment]
@mclarsen -- I totally agree.

I think BLT should have/require a `BLT_CUDA_ARCH` variable, that way we could:
* Catch this at build time and ensure it gets specified when CUDA is enabled
* Throw that variable in a `config.hpp` that we generate , that way it is easier to  check, and
* Have a better chance at introspection when we bundle libraries together

I think Spack should also require a `cuda_arch` to be set when CUDA is enabled. 

Mike C. is also maintaining his own version of spack packages. Some of his stuff has gone to the main spack, I think, but there are still things that have not made it in.

**Comment by kennyweiss** [comment]
@mclarsen -- I agree that shared maintenance of the spack packages can be helpful.

`uberenv` is a shared dependency that deals with `spack`, would it make sense to store some LLNL github spack packages there, while pushing changes back upstream?

**Comment by mclarsen** [comment]
@kennyweiss I think that is a good idea. As a  first step, we should compare  the changes to the spack packages  we have made across the libraries. I think they should all be solving the the same problems, but we  should  double check.

**Comment by cyrush** [comment]
my hope is that radiuss can help with coordination here as well.

I did a dry run upgrade of Ascent and all deps, but things where in flight with MFEM + the CEED packages, and spack itself. The hardest part in this process (let me start up my broken record) is testing post updates. If we had the tests on a wide range for LLNL systems automatically, we could upgrade faster.

**Comment by mclarsen** [comment]
@cyrush We can invest in curating spack_configs for our common systems and compilers and set up automated testing. I think that this would cover a lot of what we would need. As I found out yesterday, its pretty easy (minus some heartache) to setup automated system testing through gitlabs  CI, at least for LLNL org members.
