### ISSUE TITLE
Sanity Check TPL dependencies at the axom config level

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#243]
The current logic in the generated CMake Axom config allows for a host application to use different TPLs than the ones used by Axom. For example, a host application may be using one version of Conduit and bring in Axom that was built with a different version fo Conduit. 

https://github.com/LLNL/axom/blob/3128c6cbd68cb184202488dd85feafc467faa6cf/src/cmake/axom-config.cmake.in#L63-L70

The host-application and Axom, are typically pointing to the same TPLs, e.g., Conduit, HDF5, RAJA, Umpire, etc. 

There could be some serious complications that could arise otherwise.

In our generated CMake Axom config, we have the opportunity to catch that at the build system level, instead of allowing things to build and potentially lead to bugs that will be hard to detect and resolve downstream.

I cannot think of a real use-case where we'd want to allow for this. 

If throwing an error seems too restrictive, we should at minimum issue a warning message (and hope it is not ignored).

**Comment by rhornung67** [comment]
will reopen if needed.
