### ISSUE TITLE
Possible bug in triangle-triangle intersection algorithm

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#261]
A user-provided mesh was flagging some triangles as self-intersecting.

Based on visual inspection, the triangles do not appear to intersect.

![image](https://user-images.githubusercontent.com/5626552/84957334-d35bde00-b0af-11ea-9afd-6ead39fff0b7.png)

**Comment by rhornung67** [comment]
Is some non-zero "fuzz" tolerance used, or do the red triangles intersect at a vertex (it's hard to tell from the image)?

**Comment by kennyweiss** [comment]
I'm still looking into it, but the mesh vertices have been "welded" before checking for self-intersections and the common vertex is shared between the two triangles.  I.e. there are only 5 unique vertices for the two triangles that are reported as self-intersecting.

However since nearly all the triangles in this mesh look similar, I suspect that there is a bug in one of the subcases of the triangle-triangle intersection algorithm, possibly related to fuzzed tolerances and/or specific triangle orientations.

**Comment by gzagaris** [comment]
Yeah -- the intersection code probably is not distinguishing between overlapping triangles and "valid" intersections, e.g., vertex- or edge- intersections

**Comment by rhornung67** [comment]
But, it's weird that it would happen in this one case and not a bunch of others, no?

**Comment by kennyweiss** [comment]
Actually, I have a few other meshes from the same user with similar problems.  (sorry for not mentioning that above.

For all of these meshes:
* `meshlab` is not reporting any self-intersections
* the `InOutOctree` is successfully able to initialize and categorize all regions as inside/outside

**Comment by kennyweiss** [comment]
The problem ended up being related to a hidden "magic" tolerance deep within the `intersect(Triangle,Triangle)` implementation.  I exposed this to the user in #265.

#### Details:
The default tolerance was `1E-12` and the problematic triangles in the above case were within `3E-12` of each other. All problems with the meshes provided by this user went away when I set the tolerance to `1E-08`.

Note also that above mesh is pretty far from the origin:
```
[INFO] Mesh bounding box: { min:(-8873.55,-14673.2,111294); 
                            max:(3140.59,-11252.2,112666); 
                            range:<12014.1,3420.99,1371.77> } 
```

**Comment by gzagaris** [comment]
Ugh! hidden "magic" tolerances strike again 😄
