### ISSUE TITLE
More flexibility needed in contents of SPIO root files

### ISSUE THREAD

**Issue by nselliott** [LLNL/axom#264]
IOManager automatically places some data in the root files that is based on the schema for the Conduit blueprint index.  Even if the customer application is not using the blueprint, something along these lines is necessary when an application is parsing the root file to get the meta-information about where to find data to load, so it is reasonable to use the blueprint as the model to follow.  However, the current implementation hard-codes some things that can interfere with providing sufficient flexibility to users, and there are some upcoming changes to the blueprint index that we will
need to take into account.

Conduit github issue about blueprint index changes, which are intended to better support applications with multiple domains per rank.  It is labeled for AMR but also relevant for any multi-domain/rank application:  https://github.com/LLNL/conduit/issues/476

The current schema looks like this:
```
{
    "number_of_files": /* int */, // number of data files
    "number_of_trees": /* int */, // number of domain trees per file--ranks per file in SPIO terms
    "file_pattern": /* string */, // template for data file strings
    "tree_pattern": /* string */, // template for domain tree paths
}
```

The entry I'm focused on is "tree_pattern".  We currently hardcode it as "datagroup_%07d" with the integer substitution being the writing rank.  This won't be sufficient when moving away from a single-domain/rank assumption.  The proposed new schema will use integer format substitions for both the rank and a domain ID.   The base name "datagroup" also is obsolete as it comes from the old class name DataGroup, and the new schema will probably need to allow users a way to specify what they want the tree pattern string to be, including using paths.  Either we could change the API to make the user set this string explicitly, or we could have a default that could be overridden by the user.

I don't have a specific proposal for changes right now, but this issue can be used to track and discuss what changes are needed.

**Comment by rhornung67** [comment]
@nselliott is this issue resolved and can be closed?

**Comment by nselliott** [comment]
Closing this, as the specific issues here were addressed by the PR mentioned here or rendered obsolete by conduit's changes to the blueprint index. If a need for more changes is discovered, there should be a new issue posted.
