### ISSUE TITLE
Move AXOM_DEBUG compiler define to axom/config.hpp

### ISSUE THREAD

**Issue by white238** [LLNL/axom#279]
The AXOM_DEBUG compiler define is currently determined by the build type (i.e. it is turned on in Debug and RelWithDebInfo builds and off otherwise), and is added to the compilation flags, but not to axom/config.hpp.

Since it is a configuration option, it should be added to axom/config.hpp. 

We might also consider adding a cmake option to override the default behavior of this compiler define.

**Comment by kennyweiss** [comment]
Resolved in #699 by attaching the `AXOM_DEBUG` compiler define to axom's `core` component
and adding a config variable `AXOM_DEBUG_DEFINE` to override the behavior of `AXOM_DEBUG`.

See #440 for reasons we were not able to add `AXOM_DEBUG` to `axom/config.hpp`
