### ISSUE TITLE
Add Fortran Slic Logging example

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#29]
Add a Fortran example that illustrates how to use Slic for logging.

**Comment by kennyweiss** [comment]
@gzagaris -- when you get a chance can you please look into this?
I tried using `slic` from Fortran and ran into two problems:

1. Initialization -- `slic_is_initialized()` claimed to be true before running `slic_initialize()`.  It looks like this might be related to differences in how static initialization happens from Fortran as opposed to ``C++``.  I encountered this issue with both `gfortran` and `ifort`
2. API completeness -- It wasn't clear to me how to set the formatting for a simple logger from the Fortran side.

**Comment by gzagaris** [comment]
Thanks @kennyweiss -- I'll take a look.

The initialization issue sounds a bit alarming. 

As far as the API completeness, there are certainly gaps there, since we are not really using SLIC  from Fortran in a real application.

**Comment by kennyweiss** [comment]
Thanks @gzagaris.  This came up when I was trying to use `slic` in a new Fortran example for `tribol`.

**Comment by gzagaris** [comment]
@kennyweiss, in that case,  I suggest initializing `slic` inside `tribol` initialize() as we do in the `quest` interface for the `signed distance` and `inout`.

**Comment by kennyweiss** [comment]
This would still be a useful thing to have in the slic examples.

**Comment by kennyweiss** [comment]
Might depend on #270 

A workaround (before #270 is resolved) might be to call `slic::finalize()` at the beginning and then call `slic::initialize()`.
