### ISSUE TITLE
Add SCR back to our host-configs

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#310]
A recent PR was added to revamp our SCR usage within SPIO (#251).

When reviewing it, we discovered that we are no longer testing SCR in any of our host-configs.

We should add SCR to our LLNL host-configs and to at least one docker-based host-config, if possible.

**Comment by kennyweiss** [comment]
Based on a comment from @nselliott, it looks like we need to add `scr@2.0.0` or later.

**Comment by nselliott** [comment]
SCR is now in several of the host-configs and is exercised in testing.
