### ISSUE TITLE
Future Bug with RAJA Code in Mint

### ISSUE THREAD

**Issue by Parqua** [LLNL/axom#314]
In Mint, at the line sampled below, RAJA::statement::tile_fixed is used. At the moment, and for an indeterminate amount of time, this is the correct usage for RAJA, but the commit 
https://github.com/LLNL/RAJA/commit/ad3f19678b24e440bd4ba9c61641d06db9ebf5e7 on the RAJA develop branch moves tile_fixed from the RAJA::statement namespace to the RAJA namespace. Thus, at some point in the future, once this change in RAJA moves to release, the use in Mint will need to change.

This isn't exactly a problem that exists for Axom at the moment, but I wanted to document this, so the problem and solution are known when it arises naturally.

https://github.com/LLNL/axom/blob/c3a64b372d25e53976b3ba8676a25acc49a9a6cd/src/axom/mint/execution/internal/structured_exec.hpp#L112

**Comment by gzagaris** [comment]
Thanks @Parqua -- I am aware of the namespace changes in RAJA and I plan to make this change after RAJA is released at which point we can proceed with updating RAJA (as well as, Umpire) in Axom and making an Axom release. 

This is needed by downstream host applications that rely on RAJA, Umpire, Axom etc.

**Comment by rhornung67** [comment]
@gzagaris @Parqua FYI: here is a link to the release notes for the upcoming RAJA release. The "API Changes" section contains namespace changes we have made.

**Comment by gzagaris** [comment]
Thanks @rhornung67 -- you forgot the link, but we can figure that out 😄  

- Is a RAJA release in the plans for this week? next week?
- Is another Umpire release also in the works?

I am just trying to put the timelines in to perspective, since we would have to get a corresponding Axom release for the host code I am working on.

**Comment by rhornung67** [comment]
RAJA release will be in 2-3 weeks, hopefully. We’re trying to get our remaining PRs in.  I think the plan is to have RAJA, Umpire and CHAI all be released around the same time so we’re all using the same versions of BLT and camp. We have to coordinate with those other projects.

--Rich

**Comment by gzagaris** [comment]
> RAJA release will be in 2-3 weeks, hopefully. We’re trying to get our remaining PRs in. I think the plan is to have RAJA, Umpire and CHAI all be released around the same time so we’re all using the same versions of BLT and camp. We have to coordinate with those other projects.

Yup -- that is primarily why I was inquiring about this.

**Comment by white238** [comment]
I will be doing another BLT release today that will fix the blocking problem for umpire

**Comment by gzagaris** [comment]
Great -- thanks @white238 

By "blocking problem" you mean do not require ``CUDA_TOOLKIT_ROOT_DIR`` correct?

**Comment by white238** [comment]
> Great -- thanks @white238
> 
> By "blocking problem" you mean do not require `CUDA_TOOLKIT_ROOT_DIR` correct?

yepp! It's been fixed in develop but i just need to go through the whole set of release PR's.
