### ISSUE TITLE
Add ability to register a custom abort handler to SLIC

### ISSUE THREAD

**Issue by white238** [LLNL/axom#321]
Currently, SLIC_ERROR() and SLIC_ASSERT() call "processAbort()" which, in turn calls std::abort() or  MPI_Abort() + std::abort() when MPI is enabled. Although this is sufficient for the most part, there are some use cases, where it would be desirable to override this default behavior. For example, for supporting death tests within an MPI process, it is desirable not to call MPI_Abort(). Having the ability to register a custom abort handler to Slic could provide one solution to that.

**Comment by gzagaris** [comment]
I think we have a way to do a `setAbortOnError` to false, etc., which I think would be useful for what you are describing.

**Comment by white238** [comment]
I moved this one from Jira because it came up in Serac.  I already have the setAbortOnError and setAbortOnWarning to false, but it would be nice to be able to register a custom abort to cut down on duplicate code throughout the code base.
