### ISSUE TITLE
Remove  AXOM_USE_CXX11 compiler define

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#33]
Axom requires a ``C++11`` compiler, so we should remove all compiler guards that provide fallbacks for cases where `C++11` was not available (e.g. `#ifdef AXOM_USE_CXX11`).

**Comment by white238** [comment]
Handling this...

**Comment by kennyweiss** [comment]
Thanks @white238.  

I've already handled the ones in slam in #37.

**Comment by white238** [comment]
K... I'll revert what I have done in that directory and wait for you to merge this branch before merging mine.

**Comment by kennyweiss** [comment]
This has been resolved in #37 and #38
