### ISSUE TITLE
Add code formatting check to a CI job

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#336]
We need to add `make check` to a CI job. If `make check` fails, the CI test should fail.

Since clang-format relies on `clang 10`, this should be added to our clang-10 docker plan.

See: #337

**Comment by gzagaris** [comment]
Github Actions may be a good alternative to this -- I came across an article and it seemed that there are canned things that we could use right out-of-the-box for this and looked easy to setup....

**Comment by white238** [comment]
Fixed in #367
