### ISSUE TITLE
Modify API for primal::intersect(Segment, BoundingBox)

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#344]
A user raised a question about the API for `primal`'s intersection operator between a line segment and an axis-aligned bounding box.

Specifically, if the segment and bounding box intersection, we return _an_ intersection point between the two primitives.
However, the intersection between a segment and a bounding box will, in general, be a subset of the input segment (i.e. a `primal::Segment`) rather than a single point.

Here is the current API:
https://github.com/LLNL/axom/blob/3754a2d90ea2adbf58bc40f33ba723bb69963e47/src/axom/primal/operators/intersect.hpp#L280-L283

Should we modify the API to something like this:
```cpp
template <typename T, int DIM>
bool intersect(const Segment<T, DIM>& S,
               const BoundingBox<T, DIM>& bb,
               Segment<T, DIM>& intersection)
```

Pros:
* This will provide the user with the intersections, which they can then use for downstream processing
* The returned intersection point is essentially free to compute, since it is (mostly) an artifact of how we test for intersections

Cons:
* It will require some additional computational effort to compute the bounds of the actual intersection, which not all users will require
* The requested functionality might be more appropriate for a clipping function, e.g. `primal::clip(Segment, BoundingBox)`.

Alternate idea: Perhaps we can provide an additional function with the suggested interface, that way the extra work will only need to be performed on demand.

Note: In this case, the user _is_ actually interested in finding all the intersections between the segment and bounding box.

Tag: @s-sajid-ali

**Comment by s-sajid-ali** [comment]
How about having an extra bool argument (set to `False` by default) indicating whether the intersection should return the intersection points and returning a variable length vector filled with the intersection points if it is set to true ? That way there is no extra overhead in computing the actual intersections for use cases where that is unnecessary. Then the `clip` function (and any user interested in the actual intersection points ) can just call the intersect function with the bool argument set to `True`. 

Another issue with having a `Segment` return type is when there is only one intersection point. How would the valid intersection point be marked ? (i.e. does the result become the return segment's `source` or `target` and how is this communicated to the end-user ?)  Returning a variable length vector might be one way to unify all possibilities.

**Comment by rhornung67** [comment]
Discussed: update documentation to be more clear about design choice.

**Comment by kennyweiss** [comment]
@s-sajid-ali -- I apologize for the delayed response on this issue.  Is this issue still relevant to your work?

We discussed this during a team meeting and decided to keep the current implementation as is, i.e.:
```cpp
 template <typename T, int DIM> 
 bool intersect(const Segment<T, DIM>& S, 
                const BoundingBox<T, DIM>& bb, 
                Point<T, DIM>& ip) 
```
where the returned intersection point `ip` lies in the intersection region, when the two primitives actually intersect. The reasoning was that our current use case only requires knowledge of whether the two primitives intersect, and the computed intersection point is a by-product of how we compute the intersection, so there is no additional computational overhead.

If one needs the full intersection segment, the consensus was that this should be a new function with the following signature:
```cpp
 template <typename T, int DIM> 
 bool intersect(const Segment<T, DIM>& S, 
                const BoundingBox<T, DIM>& bb, 
                Segment<T, DIM>& ip) 
```
where the implementation can decide how it wants to find the bounds of the intersection (i.e. by clipping or by running the intersection twice).  `Segment::length()` could be used to determine if the intersection is degenerate (which would be rare in most cases).

This approach of having two separate functions seemed to us to be a good way for the user to declare their intent w.r.t. how they might use the function and if the extra work is needed.

**Comment by kennyweiss** [comment]
Update: I had a use case for this in PR #579  and found a better solution.

The new signature is
```cpp
 template <typename T, int DIM> 
 bool intersect(const Segment<T, DIM>& S, 
                const BoundingBox<T, DIM>& bb, 
                T& tmin,      // The smallest parametric coordinate of S that is within bb
                T& tmax,      // The largest parametric coordinate of S that is within bb
                const T EPS = <default_tol>)    // The geometric tolerance for determining intersections
```
These parametric coordinates are only valid when the function returns `true`.
In that case, we will have ` 0 <= tmin <= tmax <= 1`.

To retrieve the point at each of these coordinates:
```cpp
PointType minPt = S.at(tmin);
PointType maxPt = S.at(tmax);
```


Tag: @s-sajid-ali

**Comment by kennyweiss** [comment]
Note: We still have the following two overloads:
```cpp
 template <typename T, int DIM> 
 bool intersect(const Segment<T, DIM>& S, 
                const BoundingBox<T, DIM>& bb, 
                PointType& ip,
                const T EPS = <default_tol>);

 template <typename T, int DIM> 
 bool intersect(const Segment<T, DIM>& S, 
                const BoundingBox<T, DIM>& bb);
```

The former performs the interpolation for us, and has the same signature as before.
The latter is a convenience for when the user only cares *if* the two entities intersect, but not *where*.

**Comment by s-sajid-ali** [comment]
@kennyweiss Thanks for the fix !
