### ISSUE TITLE
Update Docker Images to RAJA-v0.12.1 & Umpire-v4.0.1 

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#345]
Our Docker images are currently using an older version of RAJA from develop and Umpire-v2.1.0. 

PR #325 updates Axom to use the present latest releases of RAJA and Umpire, but,  remains backwards compatible to older versions. 

However, we don't have RAJA-v0.12.1 and Umpire-v4.0.1 in any of our Docker images and hence our CI is not currently testing Axom against the latest RAJA and Umpire versions.

**Comment by white238** [comment]
Fixed in #397
