### ISSUE TITLE
Update compiler specs on RZAnsel

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#347]
On RZAnsel plaform, we are currently using:

- clang@8.0.1
- IBM XL C/C++ 2019.08.20
- NVIDIA CUDA 10.1.243
- gcc@7.3.1

We should update to:

- clang10
- IBM XL C/C++ 2020.09.17 (there have been some bugfixes to the compiler)
- NVIDA CUDA 11

We may also want to revisit if we want a GCC spec on this platform (I think it would be a less common option) and consider either removing the GCC spec or updating it.

**Comment by rhornung67** [comment]
Survey code teams to see what compilers they are using.  Stick with what they are using in day-to-day development and production uses.

**Comment by rhornung67** [comment]
Focus on this after the release.

**Comment by kennyweiss** [comment]
Closing this issue. Will create a new one to move to compilers from shared radiuss-spack configs.
