### ISSUE TITLE
IBM XL C++ compiler bug

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#348]
After updating to RAJA-v0.12.1, the following code used in one of the Axom tests seems to trip the IBM XL C++ compiler:
https://github.com/LLNL/axom/blob/a42588b2d03cda0c9660489869e6577d2631bb05/src/axom/spin/tests/spin_bvh.cpp#L263-L291

The code compiles, but there is a SIGSEGV when accessing one of the captured arrays, `xc` and `yc`. These arrays are either allocated in UM when testing on the GPU or Host when testing on the CPU. The code fails the same in both cases, so this is not pertaining to GPU access.

This failure happens when using both:
- IBM XL C/C++ 2019.08.20, and
- IBM XL C/C++ 2020.09.17 (which is newer and has some bug fixes)

Notably:
- The code works correctly when compiled with older versions of RAJA
- Works with RAJA-v0.12.1 and all other compiler specs (e.g., clang, gcc, etc.)

The only way to fix this was to re-write the loop with avoiding lambdas. PR #325 introduces this workaround.

We should investigate if we can provide a standalone re-producer to provide to IBM.

**Comment by kennyweiss** [comment]
@kanye-quest -- I think you resolved this in #601.
Could you please comment on this and possibly close this issue?

**Comment by kanye-quest** [comment]
Yeah, looks like we were running into an edge case with XL's handling of `constexpr double`. The fix was to just replace a multiplication by `ONE_OVER_2N` with a division by a `constexpr int`.
