### ISSUE TITLE
consider adding env var to our tests to appease openmpi 

### ISSUE THREAD

**Issue by cyrush** [LLNL/axom#349]
OpenMPI wants you to jump though hoops to launch more MPI tasks than cores. 

We can smooth this out by adding an OpenMPI specific env var to our tests. 

Here is the example from conduit:

https://github.com/LLNL/conduit/blob/09b49e839add9e46707c458ea463928f87a2c1c1/src/cmake/SetupTests.cmake#L190

**Comment by gzagaris** [comment]
Does it make sense for this to be handled in BLT ? i.e., When `OpenMPI` is used add the property to the test. I would imagine you would need that for any executable and not just the test.

**Comment by white238** [comment]
add `axom_add_test` that adds the environment variable to all our tests in one place

**Comment by white238** [comment]
Add this variable as well to fix the spin_bvh test per @kennyweiss :

```
        # TODO: remove when ats generates compatible jsrun commands or blast
        # handles more than 1 gpu per rank. this is here to make sure each
        # mpi rank gets an exlusive gpu (when np<=4)
        e("tide.setenv('CUDA_VISIBLE_DEVICES', '' .. mpi.rank % 4, 1)"),
```

**Comment by white238** [comment]
Is there a test for the original (read not the spin_bvh problem) so I know this is fixing something?
