### ISSUE TITLE
Support device memory in Sidre

### ISSUE THREAD

**Issue by ltaylor16** [LLNL/axom#357]
From Matt Larsen via MAPP meeting: Having a device pointer in addition to a host pointer (or just one with an attribute) would mean we could avoid copies when using the data in another package, like Ascent

**Comment by rhornung67** [comment]
We currently support this to an extent. For example, you can make two group hierarchies with the same structure and use an Umpire device allocator in on and an Umpire host allocator in the other. Of course, one would have to manually manage copies between the two (via Umpire methods) to keep the data consistent. But, I think that is unavoidable. So I think we support Matt's use case.  @kennyweiss do you agree? Would this work for MAPP?

**Comment by rhornung67** [comment]
Closing for now. Can open new issue if further support is required.
