### ISSUE TITLE
Update read-the-docs to python3

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#389]
Our read the docs builds produce the following warning:
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

**Comment by kennyweiss** [comment]
We should also add the axom logo to our read-the-docs project at the same time.

**Comment by kennyweiss** [comment]
I think this config file needs to be updated as part of this: https://github.com/LLNL/axom/blob/develop/.readthedocs.yml

**Comment by rhornung67** [comment]
Update merged to develop
