### ISSUE TITLE
SLIC enumerator Info is not prefixed properly

### ISSUE THREAD

**Issue by white238** [LLNL/axom#42]
A code ran into a conflicting symbol with SLIC's enumerator "Info" from wrapSLIC.h.

After talking to @gzagaris, we came to the conclusion that Shroud is not prefixing the individual emerators in the enumeration.  I assume this is just an oversight in Shroud and should be fixed at that level.  @ltaylor16, thoughts?

For example, this:

enum SLIC_Level {
  Info
}

should be this:

enum SLIC_Level {
  SLIC_Info
}

**Comment by ltaylor16** [comment]
I was able to update slic_shroud.yaml to change the option C_enum_member_template to include more scoping information.  I'll make this the default value in Shroud.

**Comment by ltaylor16** [comment]
Does this mean that they were using the C wrapper?

**Comment by gzagaris** [comment]
I don't think the C wrapper was used. They were just running into compilation issues since that code had symbols with the same name as the levels we use in Slic.

**Comment by ltaylor16** [comment]
I see that wrapSLIC.h is included by `include/axom/slic.hpp`, which I think is generated.  I think that the files in `interface/c_fortran` should not be included since they're intended for C.

**Comment by gzagaris** [comment]
Yes, ``include/axom/slic.hpp`` is the generated unified header. I could certainly exclude the generated C headers from being included in that file since they are intended for C/Fortran.

**Comment by gzagaris** [comment]
@ltaylor16  fixed this in 9017f6c2ff279d7a4c4037783311ba70dcd6af33
