### ISSUE TITLE
Update copyright year to 2021

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#425]

**Comment by rhornung67** [comment]
@kennyweiss I have this on my to-do list for when I rework some Axom docs. I can take it, if you prefer.

**Comment by kennyweiss** [comment]
Thanks @rhornung67 -- transferred to you

**Comment by cyrush** [comment]
that was a quick lateral pass

**Comment by rhornung67** [comment]
No problem. I could've self-assigned, but I didn't want to take the joy of a mundane task away from @kennyweiss 😆

**Comment by rhornung67** [comment]
Done and merged into develop.
