### ISSUE TITLE
Create inlet::Proxy instances from references to const objects

### ISSUE THREAD

**Issue by estebanpauli** [LLNL/axom#453]
`inlet::Proxy` instances are created from references to non-const instances of `Table`, `Field`, and `Function` (https://axom.readthedocs.io/en/develop/doxygen/html/classaxom_1_1inlet_1_1Proxy.html). However, you often have references to const instances instead. A common case is when specializing `FromInlet` (https://axom.readthedocs.io/en/develop/doxygen/html/structFromInlet.html), where you have to implement `T operator()(inlet::Table const &)`.

While typically the above is not much of a problem, it becomes a difficulty when trying to write utility functions that can be used with `Table` instances or when accessing their fields via `Proxy operator[](std::string const &)`. If possible, I would prefer to make these work with `Proxy` instances. As it stands, I have to make them function templates, potentially forcing me to include extra dependencies in a header file that I might otherwise hide in a cpp file.

It would be great if the constructors to `inlet::Proxy` were changed to take const references. It looks like all the methods on `Proxy` are marked `const`, so hopefully this is possible.

**Comment by joshessman-llnl** [comment]
This is addressed by #452:
https://github.com/LLNL/axom/blob/81584fa258143935df14f52b3d7c68fff8ce5daf/src/axom/inlet/Proxy.hpp#L48
