### ISSUE TITLE
Add compiler spec for macos mojave to our uberenv setup

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#46]
A user was unable to run `uberenv` on their macos laptop.

It looks like we will need to add a spec for mojave here:
https://github.com/LLNL/axom/blob/develop/scripts/uberenv/spack_configs/darwin/compilers.yaml

**Comment by gzagaris** [comment]
I'd advise they create their own compilers.yaml for their system and supply that when invoking `uberenv` by passing ``--compiler-yaml  path/to/compilers.yaml`` and a corresponding ``--spec %<myspec>``

That way we don't have to make any assumptions about what compilers are available on a given system and where they are.

**Comment by kennyweiss** [comment]
Thanks @gzagaris.  

I don't see that option here: https://github.com/LLNL/axom/blob/develop/scripts/uberenv/uberenv.py

Maybe it changed to  ``"--spack-config-dir"``
 https://github.com/LLNL/axom/blob/9017f6c2ff279d7a4c4037783311ba70dcd6af33/scripts/uberenv/uberenv.py#L114-L119

**Comment by gzagaris** [comment]
Yes,  you are correct, it changed recently to ``--spack-config-dir``.

You it the the path to the directory where you have your own compiler.yaml.

For example, I build TPLs on my mac like this:
```
#!/bin/bash
mydir=`pwd`
python source/axom/scripts/uberenv/uberenv.py --prefix TPL -k --spec %clang@mp4.0^conduit@master --spack-config-dir $mydir``

**Comment by cyrush** [comment]
I think its still handy to have the standard xcode compilers in our spack config. 

Spack used to be less picky, but this is how we are currently supporting 10.12 and 10.13, there is no reason not to for 10.14. 

The paths are the same, we just need to copy and update the compiler version and the os version in: 

https://github.com/LLNL/axom/blob/develop/scripts/uberenv/spack_configs/darwin/compilers.yaml

**Comment by gzagaris** [comment]
@cyrush, agreed -- doesn't hurt to have the standard xcode compilers.

**Comment by kennyweiss** [comment]
Thanks @cyrush  and @gzagaris -- we were able to figure it out by running `spack compiler find`

Spack wanted the compiler spec to be `clang@10.0.0-apple`.
