### ISSUE TITLE
Unexpected fields in Inlet

### ISSUE THREAD

**Issue by estebanpauli** [LLNL/axom#471]
There is currently no way to find unexpected fields in Inlet. For example, if a user inputs
```yaml
foo: 123
bar: 456
```
but the schema only defines the `foo` field, there is no way to see if there are extra, unexpected fields like `bar`. This can be a useful feature when validating input. In something like yaml, if a field is not defined by the schema, it can be an indication that a user miss-typed an optional field, or tried to add a field that maybe works for some objects but not others. There is currently no way to warn the user about these sorts of situations. It would be nice if there were.

**Comment by cyrush** [comment]
Yes --- Typos can also be an issue when there are optional params. 

(Like if you can optionally accept `field/z`, but some one puts in `field/zz`   -- `field/zz`  isn't wrong, but its also likely not what was intended )

In cases where this helps in ascent, we provide a surprise check, here is an example:

https://github.com/Alpine-DAV/ascent/blob/88057dc29ef1cc70b32f9dd7efa07872e4378507/src/ascent/runtimes/flow_filters/ascent_runtime_vtkh_filters.cpp#L1233

**Comment by joshessman-llnl** [comment]
After some discussion with @white238, we determined that it would be useful to support two options:

- A `strict` attribute for `Table`s that causes verification failure when unexpected fields are present
- Retrieving the global (across the Inlet hierarchy) list of unexpected fields for direct processing by the user
