### ISSUE TITLE
Better error reporting needed in Inlet

### ISSUE THREAD

**Issue by estebanpauli** [LLNL/axom#472]
Currently, when a file does not conform to an Inlet schema, SLIC is used to report errors to the log. This is less than ideal from a couple of perspectives.

The first problem is that SLIC is better suited to report problems in the application. For example, it prints out information about the source file and line number where the message originated. This is of no use for an end-user whose files are being read by Inlet. Having the file and line number of where the problem is in their input file would be much more useful. Another way in which SLIC is ill-suited for this task is that the output from Inlet will be intermixed with other application-level logging. For parsing input files, it would be better to allow the host application to report errors to the console or another file that the user can easily check that does not contain logging messages from other libraries or the application as a whole.

The second way in which SLIC makes it hard to report errors is that a common way to use Inlet is perform two phases of validation. In the first phase, basic rules such as syntax, the presence of required fields, and statically-defined valid ranges of values are checked. Inlet does this on its own or with custom validators. In the second phase, this data is converted to structs, which are then validated for proper semantics. During this second phase, it is often convenient to stop processing user input as soon as an error is detected by throwing an exception. This greatly simplifies that code, since function can be written to either return valid values or throw exceptions rather than having to return success/failure statuses. However, throwing exceptions means that the host application must now check two separate things for errors in user input: the status of the first validation via `Inlet::verify`, and whether exceptions were thrown.

There are a few possible solutions:
1. Allow Inlet to be configured to throw exceptions rather than using SLIC to report problems. Something like `inlet::ValidationError` would be quite helpful. This would solve the problem of intermixing library- or application-level SLIC messages with messages regarding bad input files. Developers leveraging Inlet could throw this same exception when doing semantic verification to solve the problem of having to detect errors in different ways.
2. Allow `Inlet` objects to be handed a `SLIC` logger which would be used for all error reporting. The application could configure this to send errors to its desired location to keep this output from getting intermixed with application logs. It could also be used to simplify the multi-phase validation by adding a method to verify that no message have been output. This method would throw an `inlet::ValidationError`, allowing for a more unified way of reporting errors.
3. Remove SLIC as a dependency to Inlet. Instead, always through an `inlet::ValidationError`. This would simplify the implementation, but would allow only a single error to be reported. Custom validators would now throw this rather than return a boolean indicating the validity of a Table.

I'm sure there are other possibilities as well, or enhancements that could be made to the above suggestions. These are just a few possibilities.

**Comment by white238** [comment]
More info from @estebanpauli :

    Right now you have to use slic. That makes it really hard, for example, to give a meaningful error message through a gui.

    While writing other parsers, I've done things like EXPECT_THAT(ex.what(), HasSubstr("myBadField")), where ex is the caught exception, and "myBadField" is a bad field I purposely put in the test. It's an easy way to validate that my error has at least some useful information that a user could use.

    With Inlet/Slic, I'm left to just check ASSERT_FALSE(myInlet.verify()).

**Comment by joshessman-llnl** [comment]
After some discussion, we plan to move forward by overloading `Inlet::verify` - `Inlet::verify(conduit::Node&)` will write verification information to its node argument in a hierarchical manner as with Conduit's blueprint verification logic.  This approach will also resolve https://github.com/LLNL/axom/issues/354

**Comment by cyrush** [comment]
If you use conduit to log things, you can also uses it's helper methods to programmatically filter out if you use the common blueprint structure. 

https://github.com/LLNL/conduit/blob/develop/src/libs/conduit/conduit_log.hpp


of course it's pretty easy to custom filter a tree as well.

**Comment by white238** [comment]
We had yet another converstation.  We are moving forward now with a vector of a new inlet structs that has fields like field name, error level, message, etc.

**Comment by rhornung67** [comment]
Wow.

**Comment by white238** [comment]
To expand on the reason discussed at the secondary meeting:

- This would be the first time exposing Conduit to an Inlet user.  At the Inlet level, the user should not have to know about conduit (or sidre for that matter) is used under the hood.
- The two users I spoke to were concerned about the burden of learning Conduit on top of already learning Inlet.
- What the users want out at this point is: where the error occurred and what error happened. So that they can report it back to their users in a specific way or handle it themselves.
