### ISSUE TITLE
Crash on bad array input

### ISSUE THREAD

**Issue by estebanpauli** [LLNL/axom#476]
Given the test below, I expect the `inlet.verify()` call to fail. Instead, it succeeds, allowing `auto values = inlet["expect_doubles"].get<std::vector<double>>();` to run, resulting in a crash.

```cpp
TEST(inlet_Inlet, badDoubles)
{
    std::unique_ptr<axom::inlet::YAMLReader> reader(new axom::inlet::YAMLReader());
    reader->parseString(R"(
    expect_doubles: [a, b, c]
    )");
    axom::sidre::DataStore ds;
    axom::inlet::Inlet inlet{std::move(reader), ds.getRoot()};

    inlet.addDoubleArray("expect_doubles");
    if (inlet.verify()) {
        auto values = inlet["expect_doubles"].get<std::vector<double>>();
        FAIL() << "Unexpectedly read " << values.size() << " values";
    }
}
```

Output:
```
***********************************
[ERROR in line 639 of file /usr/WS1/pauli2/axom/src/axom/inlet/Table.hpp]
MESSAGE=[Inlet] Field with specified pathdoes not exist: 0
** StackTrace of 20 frames **
Frame 1: axom::slic::logErrorMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
Frame 2: _ZNK4axom5inlet5Table3getIdEENSt9enable_ifIXsr6detail18is_inlet_primitiveIT_EE5valueES4_E4typeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Frame 3: std::unordered_map<int, double, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, double> > > axom::inlet::Table::getContainer<int, double>() const
Frame 4: _ZNK4axom5inlet5Table3getISt13unordered_mapIidSt4hashIiESt8equal_toIiESaISt4pairIKidEEEEENSt9enable_ifIXoosr6detail14is_inlet_arrayIT_EE5valuesr6detail13is_inlet_dictISE_EE5valueESE_E4typeEv
Frame 5: _ZNK4axom5inlet5Table3getISt6vectorIdSaIdEEEENSt9enable_ifIXsr6detail13is_std_vectorIT_EE5valueES7_E4typeEv
Frame 6: _ZNK4axom5inlet5Proxy3getISt6vectorIdSaIdEEEENSt9enable_ifIXaantsr6detail18is_inlet_primitiveIT_EE5valuentsr6detail15is_std_functionIS7_EE5valueES7_E4typeEv
Frame 7: inlet_Inlet_badDoubles_Test::TestBody()
Frame 8: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
Frame 9: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
Frame 10: testing::Test::Run()
Frame 11: testing::TestInfo::Run()
Frame 12: testing::TestSuite::Run()
Frame 13: testing::internal::UnitTestImpl::RunAllTests()
Frame 14: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
Frame 15: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
Frame 16: testing::UnitTest::Run()
Frame 17: RUN_ALL_TESTS()
Frame 18: main
Frame 19: __libc_start_main
Frame 20: tests/inlet_Inlet_test() [0x668fd4]
=====


***********************************
Aborted (core dumped)
```

Interestingly, if I make the field required, the test passes, with the following output:
```
***********************************
[WARNING in line 85 of file /usr/WS1/pauli2/axom/src/axom/inlet/inlet_utils.cpp]
MESSAGE=[Inlet] Required Table not specified: expect_doubles/_inlet_container
***********************************
```

The field is there, but is the wrong type, so the error is misleading.

**Comment by joshessman-llnl** [comment]
Thanks for finding this!

Currently, Inlet allows for mixed types in an array, so elements in the array of the wrong type is not itself an error - the array (of items of the requested type) will just be empty.  This itself is not an error unless the array is marked required, hence the pass when you mark it as required.

The internally consistent change to the first case (when the array is optional) would be to return an empty array, though if this seems unreasonable I'm open to suggestions.

**Comment by estebanpauli** [comment]
I don't think returning an empty array would be a good approach if the type of the data is wrong. If I call `inlet.addDoubleArray("expect_doubles");`, I expect a valid document to have only double in the array (when present). Anything else should be an error. If I get back an empty array, how would I distinguish `expect_doubles: [a, b, c]` from `expect_doubles` not being defined? In the first case, the user input something invalid and should be notified. It should not be silently treated as the second case where they simply left off an optional field.

**Comment by kennyweiss** [comment]
@joshessman-llnl -- thinking about @estebanpauli's request a bit further, there might be a need/desire to mark an array-based `Field` as `homogenous()`, i.e. we want all entries to have the same type, which can be similar to the `.required()` or `.defaultValue()` annotations.
The default can heterogeneous and then the accessors can filter the entries to only return the requested type (as in #477 )

**Comment by estebanpauli** [comment]
> @joshessman-llnl -- thinking about @estebanpauli's request a bit further, there might be a need/desire to mark an array-based `Field` as `homogenous()`, i.e. we want all entries to have the same type, which can be similar to the `.required()` or `.defaultValue()` annotations.
> The default can heterogeneous and then the accessors can filter the entries to only return the requested type (as in #477 )

I think `homogenous()` should be the default. If I call `addDoubleArray(name)`, I can't imagine a use case where I would expect anything but doubles to be in there. Other values shouldn't be silently ignored.

**Comment by white238** [comment]
> > @joshessman-llnl -- thinking about @estebanpauli's request a bit further, there might be a need/desire to mark an array-based `Field` as `homogenous()`, i.e. we want all entries to have the same type, which can be similar to the `.required()` or `.defaultValue()` annotations.
> > The default can heterogeneous and then the accessors can filter the entries to only return the requested type (as in #477 )
> 
> I think `homogenous()` should be the default. If I call `addDoubleArray(name)`, I can't imagine a use case where I would expect anything but doubles to be in there. Other values shouldn't be silently ignored.

I think @estebanpauli is right.  We addDoubleArray should default to homogenous. Maybe add an addMixedArray?
