### ISSUE TITLE
Add capability to reconstruct Inlet hierarchy from a saved DataStore

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/axom#487]
Since (almost) all information about the Inlet hierarchy is stored in Sidre, it should be possible to reconstruct the Inlet hierarchy from a datastore without needing an input file.

See https://github.com/LLNL/serac/pull/317#discussion_r582132597 for an example use case

**Comment by kennyweiss** [comment]
There is a distinction between the features that Inlet supports and how users (e.g. Serac) might use Inlet.
@joshessman-llnl will explore the feature space.
