### ISSUE TITLE
Add option not to apply a View when attaching a buffer?

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#510]
The `attachBuffer()` function in `sidre::View` automatically calls `apply()` when possible.
In some cases, we might want to defer calling `apply()` until later.

Should we add a flag to this function to disable calling `apply()`, for example if one wants to call the variant of `apply` with additional options for setting strides and offsets?
To preserve the current behavior, the default value should be `true`.

### Details
Implementation of `View::attachBuffer()`:
https://github.com/LLNL/axom/blob/2de3ce8c1c505dfe7ce6f833601e517534a29b57/src/axom/sidre/core/View.cpp#L248-L277
Alternate form of `apply`
https://github.com/LLNL/axom/blob/2de3ce8c1c505dfe7ce6f833601e517534a29b57/src/axom/sidre/core/View.cpp#L338-L345

**Comment by rhornung67** [comment]
Reopen if/when issue re-appears.
