### ISSUE TITLE
Explore logging message levels within each Slic category

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#522]
Many logging tools have different logging levels to allow users to modify the verbosity at runtime.

Slic  currently has:
* DEBUG
* INFO
* WARNING
* ERROR

Debug is automatically disabled during release builds.
Info is the only non-warning level that's always available.

One possible solution would be to add levels to (each?) category, so users could ramp these up/down as desired at run time.

This will take some care to keep the interface intuitive.

Part of this could be resolved by https://github.com/LLNL/axom/issues/713

**Comment by rhornung67** [comment]
Maybe have levels for info and debug only?

**Comment by kennyweiss** [comment]
If we did this, we'd likely need to have a convention for how to assign the different levels, e.g. what differentiates a "level 2" message from a "level 3" message?
