### ISSUE TITLE
Clearly indicate which slic and lumberjack functions use collectives

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#524]
The Slic and Lumbejack API docs should clearly indicate which slic functions/macros can use MPI collectives and which ones are always safe to call on specific ranks.

This could leak to Slic's `LogStream` derived types, such as `LumberjackStream`.

In particular, `slic::flush()` is a collective operation.

1. Make comment in the doxygen
2. Make a table in sphinx of calls which are collective, making it clear to users which ones have to called on all ranks

**Comment by white238** [comment]
https://github.com/LLNL/axom/issues/26
