### ISSUE TITLE
Non-existant INTERFACE_INCLUDE_DIRECTORIES in important targets cause CMake failures

### ISSUE THREAD

**Issue by white238** [LLNL/axom#530]
I keep running into this from our imported targets (Conduit in this case but I don't think they are doing anything wrong per-say).  Basically CMake is okay with a directory not existing for a build which you then export in your install.  It however is not okay with it being imported and then used in any follow up projects (Axom in this case).  This continues to plague me in different OS's.

We should probably fix this in the base packages and filter the directories before they are exported but in the meantime filter any incoming targets.

Related Github conversations:

https://github.com/spack/spack/pull/23377#issuecomment-830464468
https://github.com/LLNL/serac/pull/456/commits/a0e92264d101986f24d8239a6863a19f29db60c7
https://github.com/LLNL/conduit/issues/679

**Comment by cyrush** [comment]
I would like to get to the bottom of the source of the empty. 

Lots of moving pieces since conduit `0.7.1` with respect to MPI, etc. I want to make sure it's not due to this.
