### ISSUE TITLE
Remove `llnl_scripts/batch_scripts` directory?

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#536]
We have scripts in `<axom>/llnl_scripts/batch_scripts` to build and test axom and its TPLs using several configurations on several platforms. The makefile to run them does not appear to work and it is not clear if anyone is using these scripts.

* Is anyone using these scripts?
* Does anyone object to removing them?

**Comment by rhornung67** [comment]
I don't see why we should keep them if they don't work. If someone is using them, it's not clear what they are doing?

**Comment by kennyweiss** [comment]
That's my take as well.  Just wanted to make sure I wasn't missing something.

**Comment by kennyweiss** [comment]
I updated these scripts and removed the broken Makefile in #502.

I decided the batch scripts had utility since they captured info like banks and partitions and can be submitted without keeping a terminal open.

**Comment by kennyweiss** [comment]
Closing the issue for now -- I updated the batch scripts and removed the broken `Makefile`.
