### ISSUE TITLE
SCR CI failures

### ISSUE THREAD

**Issue by nselliott** [LLNL/axom#538]
I merged https://github.com/LLNL/axom/pull/532 after it passed the CI checks, but now I see that the subsequent CI check on develop failed.  I think this is an intermittent failure that is caused by two tests, spio_scr and IO_SCR_Checkpoint_ex, running concurrently and conflicting with each other as they create and access cache directories that SCR creates under the hood.  I don't think SCR can work correctly in this mode.  This doesn't happen if the tests run in sequence.

I think the emergency fix is to suppress spio_scr--the other one is more important--and then figure out if there's a way to make this work with both tests.

**Comment by adammoody** [comment]
If this is showing up because multiple job steps are running on the same node at once within the same job allocation, you might be able to hack things by setting ``SCR_CNTL_BASE`` and ``SCR_CACHE_BASE`` so that each job step is using separate node-local directories.

**Comment by nselliott** [comment]
Resolved my combining SCR tests into one executable.
