### ISSUE TITLE
Add a config option to guard against building axom's tools

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#560]
A user requested adding a guard for axom to not build its tools like `mesh_tester` and `convert_sidre_protocol` (in `axom/src/tools`).

Should this use an existing flag, like `AXOM_ENABLE_EXAMPLES` or a new one like `AXOM_ENABLE_TOOLS` ?

**Comment by rhornung67** [comment]
I would say that it should be a new CMake variable like what you proposed. Building examples is a separate case.
