### ISSUE TITLE
Please use external 'fmt': bundled 'fmt' headers conflict with pre-installed fmt headers

### ISSUE THREAD

**Issue by yurivict** [LLNL/axom#561]
It conflicts with pre-installed ```fmt```:
```
$ make install
===>  Installing for axom-0.5.0
===>  Checking if axom is already installed
===>  Switching to root credentials for 'install' target
===>   Registering installation for axom-0.5.0
Installing axom-0.5.0...
pkg-static: axom-0.5.0 conflicts with libfmt-7.1.3 (installs files into the same place).  Problematic file: /usr/local/include/fmt/chrono.h
```

```fmt``` packages are available on about every distro: https://repology.org/project/fmt/versions

**Comment by yurivict** [comment]
As a side-note: you install headers that unnecessarily include ```fmt/*.h``` headers. ```fmt``` is just a formatting library and users should be able to include their own ```fmt``` headers if they need them.

**Comment by white238** [comment]
We install these headers for ease of use for a few of our downstream customers.  We should however put them under `include/axom` so as to not conflict with existing `include/fmt`.

**Comment by yurivict** [comment]
> We install these headers for ease of use for a few of our downstream customers.

If there are distros without ```fmt``` packages, maybe a better way is to add such packages there?

> We should however put them under include/axom so as to not conflict with existing include/fmt.

This would still be error-prone because of the possibility of confusion with pre-installed ```fmt``` headers.

**Comment by cyrush** [comment]
example of custom namespace to avoid collisions:

https://github.com/LLNL/conduit/blob/a245212bd2d8057f4519e40cb3ad518a8432b51a/src/thirdparty_builtin/fmt-7.1.0/conduit_fmt/core.h#L190

**Comment by UnitedMarsupials** [comment]
> We install these headers for ease of use for a few of our downstream customers. We should however put them under `include/axom` so as to not conflict with existing `include/fmt`.

No. You shouldn't be bundling 3rd-party code _at all_. Just list whatever you're using as a requirement. Otherwise, you'll be bundling the compiler soon too :(
