### ISSUE TITLE
Add "zip_iterator"-like object for converting SoA data to Primal primitives

### ISSUE THREAD

**Issue by kanye-quest** [LLNL/axom#604]
In #601, the `spin::BVH` API was refactored to make more use of Primal primitive types, such as `Point`, `Ray` and `BoundingBox`. However, some user codes may choose to layout these primitives in memory as a structure-of-arrays, which would potentially necessitate an additional allocation to convert to an array of Primal types.

Instead, it was proposed that we add a `zip_iterator`-like type to Primal, which would allow this SoA data to be converted to corresponding Primal primitives on-the-fly. This would avoid imposing specific restrictions on data layout within user code, but still allow for the usage of Primal within the API by allowing us to generically accept any array-like iterator which produces the given Primal type.

**Comment by agcapps** [comment]
Thanks for this issue, @kanye-quest .  Well stated.
