### ISSUE TITLE
Mark single parameter constructors in primal primitives as `explicit`

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#609]
@steveg21 caught a bug in the BVH initialization where `primal::Vector`s were being implicitly constructed from `primal::NumericArray`s (nvcc complained about memory issues).

We should mark the single parameter constructors as `explicit`.

Examples include:
* https://github.com/LLNL/axom/blob/57a6ef7ab50e113e4cf4b639657eb84ff10789c0/src/axom/primal/geometry/Vector.hpp#L133
* https://github.com/LLNL/axom/blob/57a6ef7ab50e113e4cf4b639657eb84ff10789c0/src/axom/primal/geometry/Point.hpp#L86
(but there are others)

Here's the offending kernel:
https://github.com/LLNL/axom/blob/57a6ef7ab50e113e4cf4b639657eb84ff10789c0/src/axom/spin/internal/linear_bvh/build_radix_tree.hpp#L172-L181
(on line 179, `centroid` is a `primal::Vector` but it's being (implicitly) assigned a `primal::NumericArray`)

**Comment by kennyweiss** [comment]
@agcapps -- did #686 resolve this issue? 
If so, please close it.

**Comment by agcapps** [comment]
Yes, #686 resolves this issue.  The `for_all ( lambda )` referenced above in @kennyweiss 's issue summary is now
https://github.com/LLNL/axom/blob/48e3ee0d7568e2d41d804d2416aa07ab64030081/src/axom/spin/internal/linear_bvh/build_radix_tree.hpp#L175-L185
The assignments (with implicit conversions) are now constructor calls.
