### ISSUE TITLE
Build axom@0.5.0 with spack@develop and xl@16.1.1.7 on lassen

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/axom#616]
I am making some progress, but I am now facing this error:

```
[ 42%] Building CXX object axom/sidre/CMakeFiles/sidre.dir/spio/interface/c_fortran/wrapIOManager.cpp.o
cd /usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-build-6yc7op7/axom/sidre && /usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/lib/spack/env/xl/xlc++ -x c++ -DAXOM_DEBUG -I/usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-build-6yc7op7/include -I/usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-src/src -I/usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-build-6yc7op7/lib/fortran -I/usr/workspace/radiuss/install/radiuss-stack/[padded-to-128-chars]/linux-rhel7-ppc64le/xl-16.1.1.7/camp-0.1.0-emm6dzjdgx5wlnsjarsi4grygz57dkua/include -I/usr/workspace/radiuss/install/radiuss-stack/[padded-to-128-chars]/linux-rhel7-ppc64le/xl-16.1.1.7/raja-0.13.0-ubrabga3n3p5uz3vyghmuoitrdxdrmbz/include -I/usr/WS1/radiuss/install/radiuss-stack/[padded-to-122-chars]/linux-rhel7-ppc64le/xl-16.1.1.7/conduit-0.7.2-kgmbmxwmwblt3gr2abnbw675x2r4cokb/include -I/usr/WS1/radiuss/install/radiuss-stack/[padded-to-122-chars]/linux-rhel7-ppc64le/xl-16.1.1.7/conduit-0.7.2-kgmbmxwmwblt3gr2abnbw675x2r4cokb/include/conduit -I/usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-src/src/thirdparty -I/usr/workspace/radiuss/install/radiuss-stack/[padded-to-128-chars]/linux-rhel7-ppc64le/xl-16.1.1.7/umpire-4.1.2-4icm6ls7rdid4wblvgy6jtjl2533dwal/include -I/usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-2020.08.19/include -I/usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/include -I/usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-2020.08.19/lib/XL -I/usr/workspace/radiuss/install/radiuss-stack/[padded-to-128-chars]/linux-rhel7-ppc64le/xl-16.1.1.7/conduit-0.7.2-kgmbmxwmwblt3gr2abnbw675x2r4cokb/include -I/usr/workspace/radiuss/install/radiuss-stack/[padded-to-128-chars]/linux-rhel7-ppc64le/xl-16.1.1.7/conduit-0.7.2-kgmbmxwmwblt3gr2abnbw675x2r4cokb/include/conduit -I/usr/WS1/radiuss/install/radiuss-stack/[padded-to-122-chars]/linux-rhel7-ppc64le/xl-16.1.1.7/hdf5-1.8.22-hl7fyxcpeeor3hrre6gf5lqjuzmvnofb/include -std=c++1y      -g -fPIC -qsmp=omp -pthread -std=c++14 -o CMakeFiles/sidre.dir/spio/interface/c_fortran/wrapIOManager.cpp.o -c /usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-src/src/axom/sidre/spio/interface/c_fortran/wrapIOManager.cpp
1 warning generated.
In file included from /usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-src/src/axom/inlet/LuaReader.cpp:16:
In file included from /usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-src/src/axom/inlet/LuaReader.hpp:18:
/usr/WS2/bernede1/gitlab-runner/builds/llnl-stack-e47f8392/spack/var/spack/stage/spack-stage-axom-0.5.0-6yc7op77pmemebj6rmwb53dvq42xxbim/spack-src/src/thirdparty/sol/sol.hpp:492:16: error: no type named 'make_index_sequence' in namespace 'std'
                typedef std::make_index_sequence<sizeof...(Args)> indices;
                        ~~~~~^                     
[...]
```

Briefly looking at the code, I thought there could be an `#include <utility>` missing before line 492 (it is present later in the file). But the fact it didn't show up before makes me think I'm wrong.

[lassen-blueos_3_ppc64le_ib_p9-xl@16.1.1.7.cmake.txt](https://github.com/LLNL/axom/files/6870196/lassen-blueos_3_ppc64le_ib_p9-xl%4016.1.1.7.cmake.txt)

**Comment by davidbeckingsale** [comment]
It's a C++14 thing, so you will want to make sure you are pointing at a new enough standard library. The GCC 4.9.3 one isn't new enough iirc.

**Comment by kennyweiss** [comment]
@davidbeckingsale beat me to it :)

The first thing that jumped out at me was that the compilation line has both `-std=c++1y` and `-std=c++14`.
I don't know if that's the source of this error though.

Since `std::make_index_sequence` was introduced to the `C++14` library, are you sure your config is pointing to a `c++14` library?
On some of our systems, we point to gcc@4.9.3 which is not fully compliant with `C++14`

**Comment by kennyweiss** [comment]
Do you have the following line in your spack package / host-config?

https://github.com/LLNL/axom/blob/5178cab25d656c7361ff5365b6d97dba9e69c000/host-configs/rzansel-blueos_3_ppc64le_ib_p9-xl%4016.1.1_coral.cmake#L74

**Comment by adrienbernede** [comment]
I am not familiar with xl compilers, from what you are saying, it seems I should do something similar to what we do with intel compilers and point to a gcc compiler in the spack configuration?

However that is not what Axom does in the blueos compilers config file.

**Comment by adrienbernede** [comment]
@kennyweiss, yes I do.

**Comment by adrienbernede** [comment]
I uploaded the .cmake file. I am not using xl@16.1.1_coral but xl@16.1.1.7. I have no idea if it changes something.

**Comment by kennyweiss** [comment]
It looks like the `BLT_CMAKE_IMPLICIT_LINK_DIRECTORIES_EXCLUDE` paths are different for xl@16.1.1_coral and `xl@16.1.1.7`

The former are removing
* /usr/tce/packages/gcc/gcc-4.9.3/lib64;
* /usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/powerpc64le-unknown-linux-gnu/4.9.3
	
The latter implicit paths appear to be:
* /usr/tce/packages/gcc/gcc-4.9.3/**gnu**/lib64
* /usr/tce/packages/gcc/gcc-4.9.3/**gnu**/lib64/gcc/powerpc64le-unknown-linux-gnu/4.9.3;

**Comment by white238** [comment]
thats very unfortunate but easily fixable in our spack package.  ill throw up a fix

**Comment by adrienbernede** [comment]
I did that in a branch, testing it.

**Comment by adrienbernede** [comment]
fix/bernede1/axom-xl-cpp14 in spack

**Comment by white238** [comment]
Adrien's fix here: https://github.com/spack/spack/commit/1e2cb17396ad0e3ddea1170b50fd87a19a750481

pretty sure that doesn't work.

**Comment by kennyweiss** [comment]
Look like there are still gcc@4.9.3 paths in your link line. 
These errors relate to `C++14` libraries, and gcc@4.9.3 is missing some of these features.

**Comment by adrienbernede** [comment]
Agreed. I am guessing `module load gcc/8.3.1` could be a work-around, but isn’t there something else we can do?

**Comment by adrienbernede** [comment]
@kennyweiss, based on @davidbeckingsale work (https://github.com/LLNL/Umpire/blob/ab4392961bf0914589eb91182e9d19392b31ae2d/.gitlab/lassen-jobs.yml#L100)

I tried adding the same flags, but it resulted in a failure in conduit...

I gave up and used the variants you have in Axom CI: `axom@0.5.0 +mfem ~openmp ~cpp14` and it worked.
I would feel better about building "vanilla axom" :)

**Comment by davidbeckingsale** [comment]
It might be that you need to propagate those special flags in downstream dependencies. We have special magic in our package:

https://github.com/LLNL/Umpire/blob/develop/scripts/spack_packages/umpire/package.py#L157-L161

that I think probably needs to be replicated elsewhere.

**Comment by adrienbernede** [comment]
OK, I’ll keep that at the back of my head.

For the record, I simplified and created a specific repo for spack testing of RADIUSS projects:
https://github.com/llnl/radiuss-spack-testing
With some documentation:
https://radiuss-spack-testing.readthedocs.io/en/latest/

**Comment by kennyweiss** [comment]
I have a local branch of axom (w/ 4 small changes) that I think resolves this on the language side
(The offending line is using a C++14 library feature that is not in gcc@4.93, and my workaround uses different calls)

I'll create a PR for it.

**Comment by kennyweiss** [comment]
@adrienbernede -- I posted my bugfix in https://github.com/LLNL/axom/pull/641

When you get a chance, could you please check if this resolves the issue you're seeing?

It resolved an issue for me in a clang/xlf/nvcc configuration on LLNL's `blue_os` platform which I configured with a parallel version of mfem and `AXOM_ENABLE_MFEM_SIDRE_DATACOLLECTION`
https://github.com/LLNL/axom/blob/bdbdcaad512729d9cbe8dcd4b7e770c9ec817a36/src/cmake/AxomOptions.cmake#L13

**Comment by kennyweiss** [comment]
I don't think this issue is relevant now that axom requires `C++14`.
Closing for now, but please reopen in it crops up again.
