### ISSUE TITLE
Sparsehash compile flags bleeding too far

### ISSUE THREAD

**Issue by white238** [LLNL/axom#62]
This flag is bleeding into C/Fortran files and causing a lot of warnings in gcc 8.1+

if(C_COMPILER_FAMILY_IS_GNU AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "8.1")
      if (ENABLE_FORTRAN)
        blt_add_target_compile_flags(TO sparsehash FLAGS
            $<$<NOT:$<COMPILE_LANGUAGE:Fortran>>:-Wno-class-memaccess>)
      else()
        blt_add_target_compile_flags(TO sparsehash FLAGS -Wno-class-memaccess)
      endif()
    endif()

**Comment by gzagaris** [comment]
@white238 , you fixed this in 76e86a207b5dfffc350bf41c92bf49e838d17e09 correct?
