### ISSUE TITLE
spack build errors when installing axom+raja+umpire

### ISSUE THREAD

**Issue by goxberry** [LLNL/axom#621]
While working on LiDO, I ran into something of a strange Axom build error when `spack dev-build`-ing `lido` via `uberenv`. I've attached a log that should show all of the stderr and stdout output emitted from Uberenv/Spack 
[uberenv-build-log-2021-07-31T0755-0700-with-axom-errors-for-later-diagnosis.txt](https://github.com/LLNL/axom/files/6911416/uberenv-build-log-2021-07-31T0755-0700-with-axom-errors-for-later-diagnosis.txt), in case someone else runs into this bug -- it seems to occur when building `axom@0.5.0serac~openmp~fortran-examples+mfem~shared+cpp14+lua+raja+umpire %gcc@8.3.1` using [Serac's bespoke `axom` Spack package](https://github.com/LLNL/serac/blob/737f62a4d774d1191f7be8cbf683de0815cf74c0/scripts/spack/packages/axom/package.py) at [commit `737f62a4d` in Serac's GitHub repo](https://github.com/LLNL/serac/tree/737f62a4d774d1191f7be8cbf683de0815cf74c0/). Replacing `+raja+umpire` with `~raja~umpire` seems to resolve the Axom build errors.

I realize this bug report is notably terse and incomplete -- LiDO doesn't have a critical need to fix this problem -- but wanted to report this observed build error before moving on with other LiDO work, in case someone else runs into this issue. I'm happy to provide additional details and do more diagnostic work upon request.

**Comment by rhornung67** [comment]
No longer an issue.
