### ISSUE TITLE
Porting Map to GPU

### ISSUE THREAD

**Issue by ksuarez1423** [LLNL/axom#630]
This issue is for discussion and future implementation of GPU functionality in Axom Map. Before starting this effort, I wanted to solicit opinions on current plans that I discussed with Arlie Capps on 8/5/2021.

Currently, the plan is to, first, remove all functions from Bucket, Node, and Pair, and implement them separately, thus easing the process of moving data to GPU, at a level where user API is unaffected. Once this is done, I would want to test on CPU, and get a PR out for the change.

After that, I would want to start protyping a secondary class, called MapView. This class would exist to be allocated on GPU to allow interaction with the Map data structure without running into problems with the virtual function tables, which would arise with trying to use the current Map on GPU.

MapView would have one member variable, which is a pointer to the array of Buckets that acts as data storage for Map. It would have functions to be able to read the Map, but no capability to modify it, for this first version. One uncertainty is the question of if it should be allowed to assign new values to key-value pairs -- this would not require importing and updating metadata of changing map size, but would require implementing the locking on GPU.

Does this plan seem reasonable? Are there major problems clear on its surface? Should value assignment be part of the first MapView version, or should focus be put on the simpler read-only model to start? I want to get opinions on answers for these questions before starting development.

**Comment by kennyweiss** [comment]
Discussion moved to #574
