### ISSUE TITLE
Axom build errors when compiling data_collection_util.cpp

### ISSUE THREAD

**Issue by alecampos2009** [LLNL/axom#632]
I used to be able to compile axom with
    -D AXOM_ENABLE_ALL_COMPONENTS=OFF 
    -D AXOM_ENABLE_SLIC=ON 
    -D AXOM_ENABLE_SIDRE=ON 
    -D MFEM_DIR=my_mfem_directory
    -D AXOM_ENABLE_MFEM_SIDRE_DATACOLLECTION=ON 

Now, when I use those settings, Axom tries to compile data_collection_util.cpp and then gives an error stating that axom/primal.hpp can't be found. Seems like the code is trying to compile data_collection_util.cpp even if the configuration was set up so that primal would not be included.

Does this mean that if I now want to use the MFEM Sidre data collection functionality I also need to install primal? Should the logic in axom/src/tools/CMakeLists.txt be updated so that data_collection_util.cpp is compiled only if primal was compiled as well?

**Comment by kennyweiss** [comment]
Thanks @alecampos2009 -- yes `data_collection_util` also depends on `primal`.

I'll add the extra check to the build system, but in the meantime, I think adding `-DAXOM_ENABLE_PRIMAL=ON` to your config line should resolve this for you.

**Comment by alecampos2009** [comment]
Great, thanks @kennyweiss !
