### ISSUE TITLE
Review component dependencies

### ISSUE THREAD

**Issue by white238** [LLNL/axom#634]
Twice in the last month we have run into cases where turning off components led to build failures that were not easy to realize they were missing a required component.

We should review that our build system outputs easily identifiable error message in all cases.  This is already enabled but maybe doesn't catch all cases.  For example:

https://github.com/LLNL/axom/blob/0aa52b61026327488b56608289a2e64421afab3d/src/axom/inlet/CMakeLists.txt#L12-L13

**Comment by white238** [comment]
#632

**Comment by rhornung67** [comment]
Seems like a reasonable solution would be to add an azure check based off of running a python script. Add details...

**Comment by white238** [comment]
closed byt #646
