### ISSUE TITLE
GitLab CI pipeline broken after slurm changes

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#637]
The handling of nested `srun` invocations within an allocation has changed in the new SLURM on LC's `toss3` platform, causing our GitLab CI jobs to fail.

Here's a sketch of the problem:
* Our CI has an outer `salloc`
* each CI job runs a python script using `srun` on this shared allocation
* Inside this script, we call `ctest`; some of the unit tests use MPI and have an inner `srun`
* The new slurm changed the ownership/sharing of resources within jobs, in particular for nested `srun` commands

Here's what this looks like in the GitLab CI logs:
```
srun: Force Terminated job 2677953
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
slurmstepd: error: *** STEP 2677953.0 ON ruby18 CANCELLED AT 2021-08-11T17:18:22 DUE TO TIME LIMIT ***
```

Digging a bit deeper into the specific messages, we discover:
```
>grep ^5: output.log.make.test.txt

5: Test command: /usr/bin/srun "-n" "4" ".../tests/blt_mpi_smoke"

5: Test timeout computed to be: 1500
5: srun: Job 2617225 step creation temporarily disabled, retrying (Requested nodes are busy)
5: srun: Job 2617225 step creation still disabled, retrying (Requested nodes are busy)
5: srun: Job 2617225 step creation still disabled, retrying (Requested nodes are busy)
5: srun: Job 2617225 step creation still disabled, retrying (Requested nodes are busy)
5: srun: Job 2617225 step creation still disabled, retrying (Requested nodes are busy)
5: srun: Job 2617225 step creation still disabled, retrying (Requested nodes are busy)
5: srun: Job 2617225 step creation still disabled, retrying (Requested nodes are busy)
```

**Comment by kennyweiss** [comment]
@adrienbernede -- have you been dealing with this too? Do you have suggestions?

**Comment by rhornung67** [comment]
Does LC have a recommendation for how to address this?

**Comment by adrienbernede** [comment]
@kennyweiss I haven’t run into this issue yet, although I had noticed the LC email about this change and I was keeping the information in the back of my head.

Have you tried using `--interactive` in the "top level" srun, like suggested at the time?

**Comment by kennyweiss** [comment]
Thanks @adrienbernede -- I responded offline

**Comment by kennyweiss** [comment]
From @adrienbernede's response, we should confirm that we're actually reusing our allocations as expected in our GitLab CI setup for toss3.
