### ISSUE TITLE
Explain why CI is failing due to time limit of Ruby

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/axom#640]
@white238 @kennyweiss,

I was checking on the Axom CI this morning to see if things went well.
I noticed that **the scheduled pipeline on develop is failing**, due to time limit on certain ruby jobs.

Those jobs get an individual 25 min allocation, but the job is failing after 1 hour, due to the gitlab time-out.
That tells me that most of the time is spend waiting for the allocation.

I am pretty sure that’s because there are 6 ruby jobs, each asking for to run on `pdebug` while this queue has a limit of 2 (?) jobs per user. That explains why 4 of the jobs pass in the 1h time slot, but not the other 2.

Now, for the fix:
- A quick one is to increase gitlab timeout (Settings/CI-CD/General Pipelines/Timeout) to 2 hours (1.5 would be enough, but there is not strong incentive to keep that as short as possible).
- Another solution is to not ask for `pdebug`. Allocation will take longer, so the timeout may need to be increased anyway to cover for the allocation time.
- The last solution I see would be to share an allocation of several nodes, possibly on pdebug (although there is a limit on the number of jobs too).

**Comment by rhornung67** [comment]
@adrienbernede have you thought more about what may be the best way to resolve this issue? Please let us know. Thank you.

**Comment by adrienbernede** [comment]
@rhornung67 have you applied (1) ? This is free and will make the pipeline pass.

Then, to really solve the issue I prefer (3) over (2),because I like to get the jobs to go as fast as possible,
But it may not be your preference: for nighty tests asking for pdebug may not be a good practice.

**Comment by rhornung67** [comment]
We will give 1 a try as a short term fix and discuss 2 and 3 as longer term possibilities. Thanks.

**Comment by kennyweiss** [comment]
Closing the ticket for now, but I suspect we might need to revisit in the future.
I updated the gitlab timeout to 1.5 hours, as suggested by @adrienbernede, 
and also increased each test's time to 1 hour in #689.
