### ISSUE TITLE
Make Primal functions device-callable

### ISSUE THREAD

**Issue by steveg21** [LLNL/axom#642]
Tribol needs the following functions callable from a device (i.e., AXOM_HOST_DEVICE):

Primal::BoundingBox::dimension()
Primal::BoundingBox::getLongestDimension()
Primal::BoundingBox::expand()

it makes sense to do this for isValid() and shift() too.  Also, please add AXOM_HOST_DEVICE to
Primal::Point::to_array()
Primal::NumericArray::to_array()
Primal::Vector::negate()

**Comment by rhornung67** [comment]
@steveg21 do you want us to add the host-device decoration to these methods? Or, does it work better for you to make an Axom branch and add them to that branch as you find them and put up a PR?  Either way works for us.
