### ISSUE TITLE
Add missing sidre group methods

### ISSUE THREAD

**Issue by rhornung67** [LLNL/axom#674]
For consistency with other methods, we should add methods to the Group class: 
* `destroyGroupAndData()`
* `destroyGroupsAndData()`
* `destroyGroupSubtreeAndData()`
* `destroyGroupSubtreesAndData()`

See https://github.com/LLNL/axom/issues/100 for additional context

**Comment by nselliott** [comment]
I have the following methods in progress.  The `AndData` signifies that each will use the existing `destroyViewAndData` when destroying a View.  This will destroy any Buffer that becomes attached to zero Views upon the destruction of its last View.

-  `void destroyGroupAndData(const std::string& path);`
-  `void destroyGroupAndData(IndexType idx);`
These destroy a specific Group and its entire subtree.

- `void destroyGroupsAndData();`
This destroys all Groups owned by `this` Group.  The Views directly owned by `this` are not affected.  There is an analogous `destroyViewsAndData()` already in the code.

- `void destroyGroupSubtreeAndData();`
This destroys the entire subtree of `this` Group, both Views and Groups.  `this` remains in existence as an empty Group.

At the top of this issue there is also the suggestion `destroyGroupSubtreesAndData`, but I am not sure what this would mean that is not redundant with what I have described here.  Is there something more needed that I am overlooking?
