### ISSUE TITLE
Ensure Umpire usage is correctly guarded in Axom

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#679]
@rhornung67 observed that there are several places in the code that are not properly guarded against Umpire not being present in configurations that have `RAJA` but not `Umpire`.

We can test this by using a configuration with `RAJA` that does not have `Umpire`.

**Comment by kennyweiss** [comment]
I think I addressed this in https://github.com/LLNL/axom/pull/983 but we're not testing this in our CI. 
Perhaps we should add an extra CI test to catch regressions?

**Comment by rhornung67** [comment]
Add a test, not build another configuration to test.

**Comment by agcapps** [comment]
@rhornung67 , @kennyweiss , my understanding is that we want RAJA and Umpire to both be optional dependencies for Axom, independent of each other.  That is, we want to support RAJA+Umpire, RAJA, Umpire, and neither.  Correct?

**Comment by rhornung67** [comment]
I think that is correct. I don't know which projects want to use the various combinations, however.
