### ISSUE TITLE
Fix intel@19 build

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#681]
Our `intel@19` build is broken on LLNL's toss3

I'm seeing lots of error messages like:
```cpp
<axom>/src/thirdparty/axom/fmt/compile.h(483): error: "auto" function requires a trailing return type
  constexpr const auto& get([[maybe_unused]] const T& first,
                  ^
```

**Comment by rhornung67** [comment]
> Might be a `c++11` vs. `c++14` thing... ?

In C++11, you have to use a trailing return type for a function that declares its return type to be auto. Here you need to add something like '-> decltype(T)' after the closing paren of the function args.

**Comment by rhornung67** [comment]
> Configuring our `intel@19` host-config with `c++14` produced a compiler error with `sol`:
> 
> ```c++
> In file included from <axom>/src/axom/inlet/LuaReader.hpp(18),
>                  from <axom>/src/axom/inlet/LuaReader.cpp(16):
> <axom>/src/thirdparty/axom/sol.hpp(11475): error: an rvalue reference cannot be bound to an lvalue
>   			return r;
>   			       ^
>           detected during:
>             instantiation of "decltype(auto) axom::sol::stack::popper<T, <unnamed>>::pop(lua_State *) [with T=axom::sol::meta::unqualified_t<bool>={bool}, <unnamed>=void]" at line 8136
>             instantiation of "decltype(auto) axom::sol::stack::pop<T>(lua_State *) [with T=bool]" at line 15925
>             instantiation of "decltype(auto) axom::sol::basic_object_base<base_t>::as_stack<T>(std::false_type) const [with base_t=axom::sol::reference, T=bool]" at line 15957
>             instantiation of "decltype(auto) axom::sol::basic_object_base<base_t>::as<T>() const [with base_t=axom::sol::reference, T=bool]" at line 21245
> ```
