### ISSUE TITLE
Hip execution

### ISSUE THREAD

**Issue by rhornung67** [LLNL/axom#685]
Add support and CI testing for Hip execution (corona first, then rznevada, etc.). This will require:

- [ ] Setting up execution policies for Hip similar to what we have for CUDA
- [ ] Making sure we can support either Hip or CUDA in our code structure; i.e., we haven't made assumptions in the code about being CUDA specific.

**Comment by kennyweiss** [comment]
@bmhan12 -- has this issue been resolved? E.g. via #778 and #832.
If so, please close it.
