### ISSUE TITLE
Add `explicit` to all one-argument ctors

### ISSUE THREAD

**Issue by agcapps** [LLNL/axom#693]
Survey the code: find all the single-argument constructors where we should add the `explicit` keyword.  There may be places where we want to allow implicit construction.  We might not be able to add `explicit` to initializer list constructors.

**Comment by rhornung67** [comment]
Please add cases in the code that you see and should be discussed here:

- [ ]

**Comment by agcapps** [comment]
Done for now.  Will reopen if this bites us again.
