### ISSUE TITLE
Allocator support in PointInCell

### ISSUE THREAD

**Issue by kanye-quest** [LLNL/axom#729]
Currently, `quest::PointInCell` takes an allocator ID argument that may ostensibly be used to allocate temporary arrays. However, in practice we just allocate most of our intermediate arrays in unified memory if we're running on the GPU, since the MFEM part of the calculation has to run on the CPU.

We should replace these unified memory usages with arrays that use the allocator ID, then explicitly copy them to host-side memory if needed.

**Comment by kennyweiss** [comment]
The temporary arrays should be allocated in the execution space of the kernels.
We need to determine where the query will be run and allocate in that space.

These arrays are expected to be `O(N)` in the number of query points.
