### ISSUE TITLE
Issues with `AXOM_DEVICE_CODE` macro

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#734]
The `AXOM_DEVICE_CODE` macro is supposed to only be enabled for code that is running on a device (i.e. when `__CUDA_ARCH__` is defined).

I ran into a situation where `AXOM_DEVICE_CODE` appeared to be defined within host code. I suspect this is (somehow) related to the combination of object libraries and `CUDA_SEPARABLE_COMPILATION`, but haven't yet had a chance to track this down.

I'll try to create a reproducer.

Note: I ran into this while attempting to resolve https://github.com/LLNL/axom/issues/724

**Comment by rhornung67** [comment]
Pay attention to this.

**Comment by kennyweiss** [comment]
We suspect this is somehow related to our usage of object libraries. 
We should revisit this issue after removing object libraries in #1057.

**Comment by rhornung67** [comment]
Closing until we can define a reproducer.
