### ISSUE TITLE
Create a ListCollection on an array of strings?

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#746]
A user asked me if there is an easy way to create a `sidre::View` on an array of strings (e.g. `std::vector<std::string>>`).

I think this can be done with a `ListCollection`, but didn't see an example/test for this use case.

Presumably, it would use this function:
https://github.com/LLNL/axom/blob/cab5877121dbc467a716237eef1128c861a4baba/src/axom/sidre/core/Group.hpp#L934-L958

Would a simple modification of the following work (using `createStringView()` instead of `createScalarView()`)? 
Or are there gotchas to look out for?
https://github.com/LLNL/axom/blob/cab5877121dbc467a716237eef1128c861a4baba/src/axom/sidre/tests/sidre_group.cpp#L455-L466

**Comment by nselliott** [comment]
Can this be closed?  The test added in the PR shows a usage pattern that at least somewhat addresses the request, though consideration could be given to adding a more sophisticated feature.

**Comment by rhornung67** [comment]
I think we can close it and make a new issue if/when we need to.
