### ISSUE TITLE
add group method to "deep" copy a view.

### ISSUE THREAD

**Issue by rhornung67** [LLNL/axom#769]
Specifically Group::copyViewAndData(view, new_view_name = 0)

**Comment by nselliott** [comment]
We received a user request in another forum for this type of functionality.  Is this something we should move forward to develop to handle at least the more straightforward cases?

**Comment by rhornung67** [comment]
Let's discuss the use cases and implementation options at the next Axom meeting. You described some of them here in your earlier comment.  We will need to make some choices.

**Comment by nselliott** [comment]
From meeting discussion, we'll look at making sure we copy all the data into new Views that have new buffers, not necessarily duplicating all properties of the original Views, but making sure that all data seen by the original Views are fully deep copied.  Data from external Views would be copied into new Views with internal buffers.

A method to deep copy a Group will copy the full tree hierarchy under that Group, and deep copy all Views that are leaves of the tree.
