### ISSUE TITLE
Generated unified component headers do not update

### ISSUE THREAD

**Issue by white238** [LLNL/axom#785]
A user reported that when swapping Axom commits, the generated unified component headers (`core.hpp`) was not regenerated between running cmake commands in the same build directory.

~~Reproducer:~~ This has been confirmed to not reproduce.

```
cd build
cmake ...
// Create noop header in the core component (or go fancy with it, who am I to stop you)
// Add header to the core component header list in src/axom/core/CMakeLists.txt
cmake ...
// look at core.hpp in the build directory and notice no mention of the new header
```

**Comment by kennyweiss** [comment]
@white238 -- can you please clarify the third line?
```// Add header to the core component```

Specifically, for this reproducer, does one modify `<axom>/src/core/CMakeLists.txt` to add the new file to the list of headers in core? I would assume that you need to modify this file to get CMake to regerate the unified component header.

**Comment by samuelpmishLLNL** [comment]
I'll try to explain what I think is happening: Serac has a directory structure that looks like this:

```
├── serac
│   ├── axom_v2
│   ├── src
├── serac_libs                                                                      
│   ├── gcc-9.3.0                                                                   
│   │   ├── axom_v1 
```

We support two build options for axom: 
- as a submodule w/ `add_subdirectory` (using `serac/axom_v2`)
- using an installation provided by `spack` (using `serac_libs/gcc-9.3.0/axom_v1`). 

If I configure serac to use the submodule version, 
```
serac$ cmake . -DUSE_AXOM_AS_A_SUBMODULE=ON
```
then axom generates a bunch of headers (?) and puts them in the build directory:
```
├── serac
│   ├── axom_v2
│   ├── src                                                                      
│   ├── build                                                                       
│   │   ├── include                                                                 
│   │   │   ├── axom                                                                
│   │   │   │   ├── config.hpp                                                      
│   │   │   │   ├── core.hpp                                                        
│   │   │   │   ├── inlet.hpp                                                       
│   │   │   │   ├── klee.hpp                                                        
│   │   │   │   ├── lumberjack.hpp                                                  
│   │   │   │   ├── mint                                                            
│   │   │   │   ├── mint.hpp                                                        
│   │   │   │   ├── primal.hpp                                                      
│   │   │   │   ├── quest.hpp                                                       
│   │   │   │   ├── sidre.hpp                                                       
│   │   │   │   ├── slam.hpp                                                        
│   │   │   │   ├── slic.hpp                                                        
│   │   │   │   └── spin.hpp                                                        
│   │   │   └── serac                                                               
│   │   │       └── serac_config.hpp 
├── serac_libs                                                                      
│   ├── gcc-9.3.0                                                                   
│   │   ├── axom_v1 
```

but now if I reconfigure cmake to use the spack installation:

```
serac$ cmake .
```

all the headers from axom_v2 still exist in the build directory and conflict with the ones in the other installation:

```
├── serac
│   ├── axom_v2
│   ├── src                                                                      
│   ├── build                                                                       
│   │   ├── include                                                                 
│   │   │   ├── axom                                                                
│   │   │   │   ├── config.hpp                                                      
│   │   │   │   ├── core.hpp                                                        
│   │   │   │   ├── inlet.hpp                                                       
│   │   │   │   ├── klee.hpp                                                        
│   │   │   │   ├── lumberjack.hpp                                                  
│   │   │   │   ├── mint                                                            
│   │   │   │   ├── mint.hpp                                                        
│   │   │   │   ├── primal.hpp                                                      
│   │   │   │   ├── quest.hpp                                                       
│   │   │   │   ├── sidre.hpp                                                       
│   │   │   │   ├── slam.hpp                                                        
│   │   │   │   ├── slic.hpp                                                        
│   │   │   │   └── spin.hpp                                                        
│   │   │   └── serac                                                               
│   │   │       └── serac_config.hpp 
├── serac_libs                                                                      
│   ├── gcc-9.3.0                                                                   
│   │   ├── axom_v1                                                     
|   │   │   ├── include                                                             
│   │   │   │   └── axom                                                            
│   │   │   │   │   ├── config.hpp                                                    
│   │   │   │   │   ├── core.hpp                                                     
│   │   │   │   │   ├── inlet.hpp                                                    
│   │   │   │   │   ├── klee.hpp                                                     
│   │   │   │   │   ├── lumberjack.hpp                                               
│   │   │   │   │   ├── mint                                                         
│   │   │   │   │   ├── mint.hpp                                                     
│   │   │   │   │   ├── primal.hpp                                                   
│   │   │   │   │   ├── quest.hpp                                                    
│   │   │   │   │   ├── sidre.hpp                                                    
│   │   │   │   │   ├── slam.hpp                                                     
│   │   │   │   │   ├── slic.hpp                                                     
│   │   │   │   │   └── spin.hpp 
```

so, it's unclear when you say `#include "axom/core.hpp"` whether or not you're getting the header from v1 or v2.

**Comment by samuelpmishLLNL** [comment]
It's worth noting that this conflict can be avoided by completely deleting the build directory when reconfiguring cmake, but it is surprising to me that these axom headers are being generated, rather than just being part of the repository.

Out of curiosity, what is the motivation for generating headers like `core.hpp` at configure time, rather than just having it be a regular source file under version control? Typically, I expect code generation to be used only as a last resort where other simpler practices don't work.

**Comment by white238** [comment]
> @white238 -- can you please clarify the third line? `// Add header to the core component`
> 
> Specifically, for this reproducer, does one modify `<axom>/src/core/CMakeLists.txt` to add the new file to the list of headers in core? I would assume that you need to modify this file to get CMake to regerate the unified component header.

updated to be more clear

**Comment by cyrush** [comment]
@samuelpmishLLNL this is generating header files that reflect the library options as configured. 

Here is the source:
https://github.com/LLNL/axom/blob/develop/src/axom/config.hpp.in

This is common practice to provide compile time info to down steam users of the library.

**Comment by kennyweiss** [comment]
I agree with @cyrush that if you're reconfiguring in this way, the best course of action is to start from a clean build directory.

Having said that, it sounds like there might still be an issue with triggering the component-specific headers, as in @white238's original issue description.

**Comment by samuelpmishLLNL** [comment]
@cyrush I understand why config.hpp is generated at configure time: it has definitions that are dependent on user-specific paths and options:

```
$ cat axom/config.hpp
...
/*
 * Axom source location
 */
#define AXOM_SRC_DIR "/home/sam/code/serac/axom/src"
#define AXOM_BIN_DIR "/home/sam/code/serac/build"
#define AXOM_DATA_DIR "/home/sam/code/serac/axom/data"
```

I was asking about `core.hpp` and similar, which don't appear to have any such user-specific information that require generation at configure time:

```
$cat axom/core.hpp
...
#include "axom/core/utilities/AnnotationMacros.hpp"
#include "axom/core/utilities/BitUtilities.hpp"
#include "axom/core/utilities/FileUtilities.hpp"
#include "axom/core/utilities/StringUtilities.hpp"
#include "axom/core/utilities/System.hpp"
#include "axom/core/utilities/Timer.hpp"
#include "axom/core/utilities/Utilities.hpp"
#include "axom/core/utilities/About.hpp"
#include "axom/core/utilities/nvtx/interface.hpp"
#include "axom/core/utilities/nvtx/Macros.hpp"
#include "axom/core/utilities/nvtx/Range.hpp"
#include "axom/core/numerics/Determinants.hpp"
#include "axom/core/numerics/LU.hpp"
#include "axom/core/numerics/Matrix.hpp"
#include "axom/core/numerics/eigen_solve.hpp"
#include "axom/core/numerics/eigen_sort.hpp"
#include "axom/core/numerics/floating_point_limits.hpp"
#include "axom/core/numerics/jacobi_eigensolve.hpp"
#include "axom/core/numerics/linear_solve.hpp"
#include "axom/core/numerics/matvecops.hpp"
#include "axom/core/numerics/polynomial_solvers.hpp"
#include "axom/core/Array.hpp"
#include "axom/core/ArrayBase.hpp"
#include "axom/core/ArrayIteratorBase.hpp"
#include "axom/core/ArrayView.hpp"
#include "axom/core/IteratorBase.hpp"
#include "axom/core/Macros.hpp"
#include "axom/core/Map.hpp"
#include "axom/core/Path.hpp"
#include "axom/core/StackArray.hpp"
#include "axom/core/Types.hpp"
#include "axom/core/memory_management.hpp"
#include "axom/core/execution/execution_space.hpp"
#include "axom/core/execution/for_all.hpp"
#include "axom/core/execution/synchronize.hpp"
```

**Comment by kennyweiss** [comment]
Thanks @samuelpmishLLNL -- those headers are generated by our build system because the build system knows all the necessary details about which header files to include/exclude for each component based on configuration details.

The alternative would be to require developers to enter this information into the build system **and** into the header files, which, in the best case, is tedious, and in the ~~worst~~ expected case will lead to inconsistencies.

If there is a problem with the cmake triggers for these headers, we should address it directly.

**Comment by cyrush** [comment]
I see now, sounds like there are some things to iron out with the header setup for Axom.

**Comment by white238** [comment]
I'm still catching up today and don't want to lose knowledge:

https://github.com/LLNL/axom/blob/cd5866a630ada425e9f0f0de0c54c4708543f48c/src/cmake/AxomMacros.cmake#L340

should be changed to `PROJECT_BINARY_DIR`.

We should go over the project to make sure we use this instead of `CMAKE_BINARY_DIR` but I don't think this is the cause of this issue.

**Comment by white238** [comment]
Okay.. pretty sure I have tracked this down to be the `PROJECT_BINARY_DIR` vs `CMAKE_BINARY_DIR` and a combination of external TPL and submodule Axom versions.

Basically, Axom creates it's headers at the base binary dir which is left behind when you re-run cmake in the same build directory. The Serac build grabs the left-over header because it is mixed in with the Serac headers which take precedence over the TPL Axom header.
