### ISSUE TITLE
Clarify propagating behavior of axom::Array allocator

### ISSUE THREAD

**Issue by kanye-quest** [LLNL/axom#791]
# Summary

`axom::Array` propagates the underlying allocator on move/move-assignment, but not on copy construction/assignment or on swap. I think we should change this to always propagate.

## Problem

This came up while I was looking into #789. Consider these examples for `axom::Array`:

```c++
    using ArrayType = axom::Array<int>;
    ArrayType a(N, allocID);
    ArrayType b = a; // has default host allocator ID
    ArrayType c = std::move(a) // propagates allocator ID
    ArrayType d = obj.get_some_array_value(); // propagates allocator ID, either through move or elided copy
    ArrayType e = obj.get_some_array_byref(); // has default host allocator, through copy constructor
    nested_array.some_func(a); // so what happens here?
```

Note the dependence on propagation behavior on whether the copy constructor/assignment operator or the move constructor/assignment operator is called. I think having variable propagation behavior is a recipe for confusion, as it makes Array behavior harder to understand at the callsite; we should standardize on a consistent behavior for all the cases.

[This proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0177r2.html) also argues that best practice is to either always propagate, or never propagate the allocator.

## Arguing for always-propagate

Here are my arguments against no-propagation:
- No-propagation behavior doesn't feel that intuitive; the allocator ID is part of the array state, why wouldn't you copy that?
- It essentially turns the "dynamic" memory space into a "dynamic, but really host by default" space. Users that want to use allocator IDs to specify device arrays have to engage in more contortions to ensure that when arrays or objects holding arrays are copied, they stay in device space.
- The main use of not propagating is in models where allocators are passed down to nested objects - in that case, not propagating keeps the allocated space consistent. We don't do that in `axom::Array` right now, nor do I see how we'd be able to implement that for arbitrary objects.

With propagating allocator IDs, moves of memory between allocator spaces is made more explicit:
```c++
axom::Array<int> src(N, fromAllocID);
axom::Array<int> dst(N, toAllocID);
// from:
dst = src; // dependent on dst's allocator ID when this is called
// to:
dst = axom::Array<int>(src, toAllocID);
```

The only problem is that this is a breaking change -- certain areas in our code/user code may already be relying on the implicit memory moves.

**Comment by kennyweiss** [comment]
Thanks @kanye-quest -- I completely agree and the suggestion will lead to improved consistency.

We should ensure that the release notes are clear about the breaking change.
