### ISSUE TITLE
Axom's fmt still bleeds into applications

### ISSUE THREAD

**Issue by adayton1** [LLNL/axom#802]
If I include fmt/core.h and axom/fmt/fmt.hpp (the latter through axom/quest.hpp), I run into compilation errors. Basically, whichever is included first wins, and since the namespaces used are different, the code will always fail to compile.

```
In file included from axom/include/axom/fmt.hpp:15:
axom/include/axom/fmt/chrono.h:312:23: error: no member named 'fmt' in namespace 'axom'; did you mean simply 'fmt'?
      using namespace axom::fmt::detail;
                      ^

axom/include/axom/fmt/chrono.h:20:1: note: 'fmt' declared here
FMT_BEGIN_NAMESPACE
^
fmt/include/fmt/core.h:238:15: note: expanded from macro 'FMT_BEGIN_NAMESPACE'
    namespace fmt {           \
              ^
```

I doubt this is the best solution, but the only foolproof way I can think of to fix this right now is to prefix all macros in Axom's fmt with AXOM_.

**Comment by kennyweiss** [comment]
Thanks @adayton1 

>      using namespace axom::fmt::detail;

This looks like it might have been an overaggressive find/replace.

I agree with the compiler's error message that it should have simply been `using namespace fmt::detail`.
Any chance this fixes the problem?

**Comment by white238** [comment]
I spoke with @adayton1 with this.

This has to do with codes that have their own fmt that is different from ours.  Our versions preprocessor macros and defines are conflicting with theirs.  

Basically I guarded our namespaces but not the global header guards or macros.
