### ISSUE TITLE
intel@18 failing MFEMSidreDatacollection unit test

### ISSUE THREAD

**Issue by white238** [LLNL/axom#820]
Discovered in #812

**Comment by kennyweiss** [comment]
Quick update: The tests appear to be failing with intel@18 in several variations of this line:
https://github.com/LLNL/axom/blob/6cbb6a1000cbd55711611fe4e6024f5c97ffaa55/src/axom/sidre/tests/sidre_mfem_datacollection.cpp#L195

Looking a few lines up, this is with a `TRIANGLE` mesh:
https://github.com/LLNL/axom/blob/6cbb6a1000cbd55711611fe4e6024f5c97ffaa55/src/axom/sidre/tests/sidre_mfem_datacollection.cpp#L157
and an internal function (`GridFunction::GetValues()`) returns `nan`s for triangles with intel@18 for some reason.
If I switch this to `QUADRILATERAL`, the problem goes away.

I'm attempting to update from mfem@4.2 to mfem@4.4 to see if the problem goes away with a newer mfem.
If not, I'll reach out to the mfem team to see if this is something they've encountered/dealt with.
