### ISSUE TITLE
Consider renaming parallel file readers in Quest

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#851]
In `quest` we have file readers for STL and C2C files. For each of these, we also have a parallel version which reads the file in on a single rank and broadcasts the mesh to the rest of the ranks. 
Specifically, we have a `quest::STLReader` class and a corresponding `quest::PSTLReader` class, and similarly for `quest::C2CReader` and `quest::PC2CReader`.

In #850, @rhornung67 suggested that the current file/class names for the parallel/mpi extensions were too terse.

This issue is intended to discuss renaming the parallel extensions. 
The following possibilities were suggested:

1. `PSTLReader` / `PC2CReader` (current)
2. `ParSTLReader` / `ParC2CReader`
3. `ParallelSTLReader` / `ParallelC2CReader`
4. `STLReader_MPI` / `C2CReader_MPI` (suggested by @rhornung67)
5. _\<other\>_

Additional notes/factors to consider:
* At least some users are using `PSTLReader` and would need to make (minor) changes to update to a new style

**Comment by rhornung67** [comment]
Will reopen if it's considered worthy of discussion.
