### ISSUE TITLE
Failing test in Intel@18 release build 

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#90]
One of the mint tests is failing in release builds on the ``intel@18`` compiler.

```
>./config-build.py -hc host-configs/rzgenie-toss_3_x86_64_ib-intel@18.0.2.cmake -bt Release
...
>ctest -R mint_fem_single_fe -VV
...
117: [ RUN      ] mint_fem_single_fe.matrix_constructor_deepcopy
117: <axom>/src/axom/mint/tests/mint_fem_single_fe.cpp:874: Failure
117: Value of: utilities::isNearlyEqual( M.data()[i], physical_nodes[i] )
117:   Actual: true
117: Expected: false
117: <axom>/src/axom/mint/tests/mint_fem_single_fe.cpp:874: Failure
117: Value of: utilities::isNearlyEqual( M.data()[i], physical_nodes[i] )
117:   Actual: true
117: Expected: false
117: [  FAILED  ] mint_fem_single_fe.matrix_constructor_deepcopy (2 ms)
...
117:  1 FAILED TEST
1/1 Test #117: mint_fem_single_fe ...............***Failed    0.13 sec
```

Interestingly, it is passing in our ``intel@19`` host-config.

**Comment by gzagaris** [comment]
Thanks @kennyweiss -- This is due to a compiler bug. 

Apparently, intel@18 is `foobar`. Case in point, on the code that I work on, we ended up skipping intel@18 altogether and went straight to intel@19. That said, I do have a workaround and will push a fix for this shortly.

**Comment by kennyweiss** [comment]
Thanks @gzagaris. 

In that case, should axom move away from intel@18 and perhaps go back to intel@17 as our second intel host-config?

**Comment by gzagaris** [comment]
> Thanks @gzagaris.
> 
> In that case, should axom move away from intel@18 and perhaps go back to intel@17 as our second intel host-config?

That seems reasonable. We should check with other code projects to make sure. I would be really surprised if anyone is using `intel@18` at this point. 

I am not sure we need to go back to intel@17, unless folks are still using it.

**Comment by rhornung67** [comment]
Should probably check with the code team on  the first floor of B132.
