### ISSUE TITLE
[regression] Tests don't run in last revisions

### ISSUE THREAD

**Issue by yurivict** [LLNL/axom#915]
When -DAXOM_ENABLE_TESTS=ON cmake reconfigures the project but then it says that there is nothing to compile and no 'test' target:

```
-- Configuring done
-- Generating done
-- Build files have been written to: /disk-samsung/freebsd-ports/science/axom/work/.build
ninja: no work to do.
ninja: error: unknown target 'test', did you mean 'quest'?
*** Error code 1
```

Tests worked fine in ```0.6.1```.

rev. 88cac2607
FreeBSD 13.1

**Comment by yurivict** [comment]
@agcapps 
Do you know why did the 'test' target disappear?
Is it documented anywhere how to run tests?
Documentation [here](https://axom.readthedocs.io/en/develop/) doesn't have such information.

**Comment by agcapps** [comment]
@yurivict , this is on my work queue.  I just now clarified this by assigning it to myself.

At this point, before investigating, I will guess that you should clean out (delete) the compile directory, or possibly just CMakeCache.txt.  Then please rerun CMake to make sure tests get enabled.  As you may have seen, sometimes cached CMake variables interfere with generating the project.

**Comment by yurivict** [comment]
My builds are always very clean because I build in the FreeBSD ports framework and all source/build directories are recreated every time it builds.

**Comment by agcapps** [comment]
Please post sequence of commands to reproduce the error "error: unknown target 'test', did you mean 'quest'" starting from clean ports directory tree.
