### ISSUE TITLE
Convert Tioga to flux commands on 8/30

### ISSUE THREAD

**Issue by white238** [LLNL/axom#918]
From LC:

We are planning to switch most of Tioga from Slurm to Flux for workload management on Tuesday, 8/30, at 8:00 AM. We will leave a few nodes in a Slurm partition for comparison purposes. The quickest way to get started running jobs with flux is to use the various ‘flux mini’ commands and you can see what else is running on the system with ‘flux jobs -A’. See ‘man flux-mini’ and ‘man flux-jobs’ for details or the online resources at https://flux-framework.readthedocs.io/en/latest/quickstart.html#launching-work-in-a-flux-session, https://hpc-tutorials.llnl.gov/flux/, and https://hpc.llnl.gov/banks-jobs/running-jobs/batch-system-cross-reference-guides for more details.

**Comment by rhornung67** [comment]
This the only thing we had to change for RAJA for this on corona: https://github.com/LLNL/RAJA/pull/1315/files

**Comment by bmhan12** [comment]
Resolved in #932
