### ISSUE TITLE
Update BGQ host-configs

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#92]
The current bgq host-configs are not compatible with our newest version of conduit and need to be regenerated.

**Comment by gzagaris** [comment]
I thought we were dropping support for BG/Q, since it is going away (soon?).

**Comment by kennyweiss** [comment]
That's fine with me. 
But if we're dropping it, we should do it properly, e.g. remove it from our scripts and automated builds.

In this case, it was (relatively) straightforward to fix the host-config, so I did.

@rhornung67, @cyrush or others?

**Comment by rhornung67** [comment]
I know several applications have stopped testing on BG/Q systems entirely and only support it to the extent that a few users are still using it for limited work. If it's working for us now, I think we should leave it until it formally goes away.
