### ISSUE TITLE
Allow users to set a custom allocator ID in DistributedClosestPoint query

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#925]
In the distributed closest point query, we're currently using the default memory allocator associated with the current execution space. For cuda, this is currently set to unified memory. 

We should add an overload to `DistributedClosestPoint::setAllocatorID()` that allows the user to provide their own allocator. (and this function should be made `public` instead of `private`

See:
* https://github.com/LLNL/axom/blob/2c8f4ad73b2762feffa55dad906489d8493a9b19/src/axom/quest/DistributedClosestPoint.hpp#L934-L938
* https://github.com/LLNL/axom/blob/fc988d6f7da8056e65047ad312cf4b752a94940f/src/axom/core/execution/internal/cuda_exec.hpp#L62-L65
* Here's the full `setAllocatorID()` function: https://github.com/LLNL/axom/blob/2c8f4ad73b2762feffa55dad906489d8493a9b19/src/axom/quest/DistributedClosestPoint.hpp#L917-L946

In the future, we might also want to consider using a device allocator for the default cuda allocator

**Comment by gunney1** [comment]
Resolved by PRs https://github.com/LLNL/axom/pull/930 and https://github.com/LLNL/axom/pull/936.

**Comment by gunney1** [comment]
I thought I closed this with the previous comment, but it's still open.  Retrying.

**Comment by kennyweiss** [comment]
Fixed in #930 and #936.
