### ISSUE TITLE
Distributed closest-point example crashes when a rank has just 1 object point

### ISSUE THREAD

**Issue by gunney1** [LLNL/axom#933]
The crash occurs when the code tries to access element 1 of a 1-element array.
The problem is likely in special case of a `BVH` for one point.  The code fakes a 2-point array.  This is fine internally, but external code, such as the example, may be unaware of it, leading to some inconsistencies.

To reproduce,
`
bin/data_collection_util -o box_2d_1 --min -1.5 -1.5 --max 1.5 1.5 --res 100 100 -p1
examples/quest_distributed_distance_query_ex --num-samples 1 -m box_2d_1.root
`

**Comment by rhornung67** [comment]
Tray to reproduce with BVH only test.
