### ISSUE TITLE
Add `axom` namespace to all vendored libraries in CMake export

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#961]
There have been several recent issues related to exporting axom's CMake targets:
* #959 adds the `axom::` prefix to our exported `fmt` target. 
* #940 deals with the top-level `axom` target

We should also prefix our other vendored libraries, `cli11` and `sparsehash`

**Comment by rhornung67** [comment]
cli11, sol, fmt, sparsehash are all guarded and exported as Axom CMake targets.
