### ISSUE TITLE
Code should not change the root group's name

### ISSUE THREAD

**Issue by agcapps** [LLNL/axom#98]
Currently code can change the name of the root group.  However, it should not change from the empty string.  Noah has a reason for this ("the kludge"); we didn't fully discuss it for lack of time.

**Comment by nselliott** [comment]
I don't have an absolute objection to changing the root group's name.  It shouldn't be automatically changed by load(), but that is the same for any Group, and we're addressing that in #99.

There is Group::rename() in the API, which can be called to change the name of the root group, the same as any other group.  If a user code wants to do this, I thing it should continue to be allowed.  It then is the user code's responsibility to keep track of the fact that it has changed names.

The kludge relates to the current behavior of load(), which we intend to eradicate.  Currently load changes the name of the calling Group to the name of the loaded Group, except if the loaded Group's name is the empty string.  If the plan if #99 is fully implemented, this all becomes unnecessary.

There is documentation that claims the root group's name is "/".  This should be corrected.  The root group represents a concept analogous to the directory "/" in a file system, but it is not actually named "/".  In fact the path delimiter character cannot be in the name of any Group.  This is enforced implicitly when groups are constructed and explicitly when rename() is called.

**Comment by agcapps** [comment]
As long as  there are no technical problems, I agree that if a user code calls Group::rename() on a root group, the code should be able to change the root group name.

I'll work in issue #99 and come back to this one and fix the documentation.

**Comment by agcapps** [comment]
PR #111 addressed this issue and is now merged.
