### ISSUE TITLE
Improve linearization of NURBS knot spans

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#994]
When linearizing knot spans of NURBS curves, we currently uniformly sample in parameter space.
This can lead to reduced accuracy in regions of high curvature.

We should investigate adaptive sample approaches, perhaps based on curvature.

**Comment by BradWhitlock** [comment]
I added some code in C2CReader that compute derivatives and curvature for a spline. Next, I prototyped a non-uniform method of point generation that computes a curvature range for a span and then samples it for target curvature values whose "u" value is then computed. It's sampling the curvature range with a "sigmoid-like" curve that highlights low curvature a little, middle values some, and higher curvature values more. The u values are fed back into the interpolator to generate points. We're still making a user-specified number of segments per knot span as before. For small numbers of segments, prioritizing point placement using the curvature seems good. At least, it makes curves appear with smaller numbers of segments. I'm still looking at options and I need to hook up this method to some metrics to see whether it improves accuracy.
![animate_points](https://user-images.githubusercontent.com/2072964/219526974-900a99f5-2acf-4185-92ff-c0df03848871.gif)

**Comment by BradWhitlock** [comment]
I noticed that for the last span of the above spline that the front of the span would not refine, even as more line segments were added. When I looked into it more, I found that the curvature in the span was not monotonic, which is something the initial algorithm assumed. I made some changes to sample the curvature derivative within the span and look for sign changes. If sign changes are located, the code solves for the u value where the derivative changes signs (a min or max). These values are used to partition the span into smaller monotonic regions and we calculate the min/max curvature more accurately. Then segments are apportioned to the intervals based on the interval lengths. The image below shows the curvature within the last problematic span.
![axom_curvature](https://user-images.githubusercontent.com/2072964/221697440-df353b31-4aa3-4353-9ce3-446c2c2d6f50.png)

I've been looking into what's needed to compute the span area directly and then breaking up the linearized span into triangles. While doing so, I've been thinking about a new algorithm that can position points while minimizing area difference.

**Comment by rhornung67** [comment]
@BradWhitlock what happens if the curvature derivative goes to zero, but doesn't change sign, such as at a saddle point? Does that cause an issue?

**Comment by BradWhitlock** [comment]
@rhornung67  - it probably would be an issue.

The curvature-only method has larger problems compared to the uniform method. In comparing these methods, I was using the area contained under the curve and bounded by a line segment between the start/end points. The area starts small (lots of error) at low numbers of segments and then approaches the true area as more segments are added.

I tried a different method today that starts with the endpoints and introduces a point in that interval (starting at the midpoint) and then iterates to where it should produce the largest area (absolute value). As more segments are added, it applies this logic to each segment and puts the point in the one that increases area the most (thinking that the faster this is done, the less error there is for shaping). Considering the areas, this method does seem to put points where they need to go and its area graph (cyan, magenta) does exceed the area for the uniform method. I'll try some other curves though to see how it does.
 
![compare](https://user-images.githubusercontent.com/2072964/226076937-5d8c6cf5-c89a-46d4-9d86-f27ca7f1e22f.gif)
![axom_linearization_area_230317](https://user-images.githubusercontent.com/2072964/226076953-eeee53a6-5f61-471d-9c0f-824eb54b6f87.png)

**Comment by BradWhitlock** [comment]
There are several improvements I've made for this recently. At the top level, the shaping driver can accept a --percent-error value that can be passed to the IntersectionShaper, which will then try to refine its mesh as needed to hit the target error (in revolved volume). The shaper gets a revolved volume from the C2C reader, computed via quadrature, and will also compute the revolved volume (truncated cones) using the linearized mesh. The ratio of these determine the percent error and the shaper will re-refine the curve to get a finer set of line segments if needed.
